IMPRO-1838 manipulate reliability table CLI
metoppv/improver pull request #1325
Opened 2020-09-01 14:59 UTC by fionaRust

* Added a new test to apply_reliability_calibration CLI. This test takes a cubelist as an input, which requires new clize functionality. It takes a cubelist as an input as the reliability table may have different lengths for the probability bin coordinate for different thresholds after the ManipulateReliabilityTable plugin. This means the reliability tables for the different thresholds can't be merged into a single cube and the ManipulateReliabilityTable plugin outputs a cubelist rather than  a cube. The ApplyReliabilityCalibration CLI needs to be able to read in the cubelist output from ManipulateReliabilityTable plugin.

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

2020-09-01 15:05 UTC, benfitzpatrick commented on improver_tests/cli/test_init.py
> +        result = inputcubelist("foo")
Codacy found an issue: [Undefined variable 'inputcubelist'](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6105320)

2020-09-01 15:05 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6105320&bid=19984885)

2020-09-02 09:47 UTC, neilCrosswaite approved these changes
An `inputcubelist` is probably to right way to do this.

Looks good to me.

2020-09-02 10:50 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- improver/cli/manipulate_reliability_table.py  1
- improver_tests/acceptance/test_manipulate_reliability_table.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6105320&bid=19984885)

2020-09-02 11:49 UTC, gavinevans requested changes
Thanks for adding this CLI, @fionaRust 👍 

This looks fine to me. I've added a few typo and docstring corrections.

2020-09-02 11:49 UTC, gavinevans commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +def test_mainpulate(tmp_path):
```suggestion
def test_manipulate(tmp_path):
```

2020-09-02 11:49 UTC, gavinevans commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +    Test mainpulation of a reliablity table
```suggestion
    Test manipulation of a reliability table
```

2020-09-02 11:49 UTC, gavinevans commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +    Test mainpulation of a reliablity table with a reduced minimum forecast count
```suggestion
def test_manipulate_minimum_forecast_count(tmp_path):
    """
    Test manipulation of a reliability table with a reduced minimum forecast count
```

2020-09-02 11:49 UTC, gavinevans commented on improver/cli/manipulate_reliability_table.py
> +"""CLI to mainpulate a relibility table cube."""
```suggestion
"""CLI to manipulate a reliability table cube."""
```

2020-09-02 11:49 UTC, gavinevans commented on improver/cli/manipulate_reliability_table.py
> +    as many bins as possible by combining bins low sample counts.
```suggestion
    as many bins as possible by combining bins with low sample counts.
```

2020-09-02 11:49 UTC, gavinevans commented on improver/cli/manipulate_reliability_table.py
> +            sufficient sample counts and monotonic observation frequency.
```suggestion
            sufficient sample counts in each probability bin and a monotonic observation frequency.
```

2020-09-02 11:49 UTC, gavinevans commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +def test_mainpulate_minimum_forecast_count(tmp_path):
```suggestion
def test_manipulate_minimum_forecast_count(tmp_path):
```

2020-09-02 12:44 UTC, bayliffe requested changes
A couple of tiny things.

2020-09-02 12:44 UTC, bayliffe commented on improver/cli/apply_reliability_calibration.py
> +    forecast: cli.inputcube, reliability_table: cli.inputcubelist = None,
The doc-string below should be modified to indicate that reliability_table can be a cube or cubelist.

2020-09-02 12:44 UTC, bayliffe commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +def test_mainpulate(tmp_path):
@gavinevans you're really against mainpulating, even though it's what all the cool kids are doing.

2020-09-02 12:44 UTC, bayliffe commented on improver_tests/acceptance/test_manipulate_reliability_table.py
> +    Test mainpulation of a reliablity table with a reduced minimum forecast count
Isn't this an increased minimum forecast count, rather than decreased?

2020-09-02 14:16 UTC, bayliffe approved these changes

2020-09-02 14:20 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- improver_tests/acceptance/test_manipulate_reliability_table.py  1
- improver/cli/manipulate_reliability_table.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6105320&bid=19984885)

2020-09-02 14:53 UTC, gavinevans approved these changes

2020-09-02 15:22 UTC, merged