Nimrod monkey patch
metoppv/improver pull request #1344
Opened 2020-09-25 13:26 UTC by cgsandford

Updates nimrod monkey patch to ignore where the patch module is unavailable, but to raise any import errors that happen within the module.

Also has updated checksums cf #1343 .

Need to address failure of GitHub actions checks before merging.

2020-09-28 15:11 UTC, MoseleyS requested changes
Hi Caroline. I think this will fix Pylint in this instance.

2020-09-28 15:11 UTC, MoseleyS commented on improver/utilities/load.py
>          from iris_nimrod_patch import nimrod, nimrod_load_rules
```suggestion
        # pylint: disable=import-error
        from iris_nimrod_patch import nimrod, nimrod_load_rules
```

2020-09-29 09:32 UTC, MoseleyS approved these changes

2020-09-29 14:08 UTC, gavinevans approved these changes

2020-09-29 15:04 UTC, merged