Construct reliability calibration mem reduction
metoppv/improver pull request #1345
Opened 2020-09-30 10:16 UTC by BelligerG

Lowers the memory cost of construct reliability calibration table from ~3.6 GB to ~2.1 GB. Increases the time from 264.074s to 266.197s.

Description

Testing:
 - [ ] Ran tests and they passed OK

2020-10-02 08:06 UTC, gavinevans requested changes
Thanks for this update, @BelligerG 👍 

This looks fine to me. I've just suggested a minor docstring update.

2020-10-02 08:54 UTC, BelligerG commented on improver/utilities/cube_manipulation.py
> +
Thanks - I'll move it up to within the lambda function

2020-10-02 09:57 UTC, bayliffe requested changes
Thanks for doing this. One more test please.

@gavinevans do you know if the aggregate reliability tables also needs work to reduce memory so we can reduce the [requested resources](https://github.com/MetOffice/improver_suite/blob/master/lib/python/mo/settings/app/__init__.py#L32)

2020-10-02 09:57 UTC, bayliffe commented on improver/utilities/cube_manipulation.py
> +        copy=True,
Can we have a unit test for this addition please. It is new behaviour for this plugin.

2020-10-02 10:06 UTC, gavinevans commented
@bayliffe Yes, the `aggregate_reliability_tables` step does currently also use more memory than ideal, as far as I'm aware, so if there was anything that could be improved in that plugin that would definitely be good.

2020-10-06 08:03 UTC, bayliffe approved these changes

2020-10-06 08:20 UTC, gavinevans approved these changes

2020-10-06 09:02 UTC, merged