Finish integer seconds
metoppv/improver pull request #1355
Opened 2020-10-16 09:10 UTC by cgsandford

Completes work to replace all unit tests using time in "hours" to use integer seconds, via the standard test cube setup functions.

Testing:
 - [x] Ran tests and they passed OK

2020-10-16 09:14 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 4
           

Complexity decreasing per file
==============================
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -7
         

Clones removed
==============
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -2
+ improver_tests/wxcode/wxcode/test_utilities.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585&bid=20622652)

2020-10-16 09:14 UTC, benfitzpatrick commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +    cube = add_coordinate(flat_cube, range(len(data)), "model_level_number", 1)
Codacy found an issue: [range built-in referenced when not iterating](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585)

2020-10-16 09:14 UTC, benfitzpatrick commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +    cube.data = np.array(heights_data).reshape(len(heights_data), 1, 1)
Codacy found an issue: [Too many positional arguments for method call](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585)

2020-10-16 09:14 UTC, benfitzpatrick commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +    cube.data = np.array(data).reshape(len(data), 1, 1)
Codacy found an issue: [Too many positional arguments for method call](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585)

2020-10-16 09:14 UTC, benfitzpatrick commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +    cube = add_coordinate(flat_cube, range(len(heights_data)), "model_level_number", 1)
Codacy found an issue: [range built-in referenced when not iterating](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585)

2020-10-16 09:27 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity decreasing per file
==============================
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -7
         

Clones removed
==============
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -2
+ improver_tests/wxcode/wxcode/test_utilities.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585&bid=20622652)

2020-10-16 09:27 UTC, benfitzpatrick commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +    cube.data = np.array(data).reshape(len(data), 1, 1)
Codacy found an issue: [Too many positional arguments for method call](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585)

2020-10-16 09:33 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -7
         

Clones removed
==============
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -2
+ improver_tests/wxcode/wxcode/test_utilities.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585&bid=20622652)

2020-10-19 12:34 UTC, bayliffe submitted a review, later dismissed
Well done for tackling the wind downscaling tests.

2020-10-21 07:19 UTC, MoseleyS requested changes
Not much to change really. Just suggested corrections to cube names to make them easier to understand in the future.

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> -            1, [n_x, n_y], 1, data=AoS, height=0, name=None, unit=1
The correct name for this cube is `"silhouette_roughness"`. I suggest we add this.

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            Sigma, "standard_deviation_of_orography_height", "m", shape=shape
The IMPROVER ancillary for this is named `"standard_deviation_of_height_in_grid_cell"`. Can you use this here please?

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            self.z0_cube = make_ancil_cube(z_0, None, "m")
I think this cube should be named `"vegetative_roughness_length"`, but I'm not confident.

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            modelorog, "orography_height", "m", shape=shape
Our ancillaries call these cubes `"surface_altitude"`. Can we change these to be consistent?

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            Sigma, "standard_deviation_of_orography_height", "m", shape=(1, 1)
Repeat of earlier cube names comments

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            modelorog, "orography_height", "m", shape=(1, 1)
Repeat of earlier cube names comments

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +        landpointtests_rc.z0_cube = make_ancil_cube(z0_data, None, "m", shape=(1, 2))
I think this can have the same z0 cube name mentioned earlier.

2020-10-21 07:19 UTC, MoseleyS commented on improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py
> +            moro_data, "orography_height", "m", shape=(1, 2)
Cube name again.

2020-10-21 07:59 UTC, benfitzpatrick commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- improver_tests/wxcode/wxcode/test_utilities.py  1
         

Complexity decreasing per file
==============================
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -7
         

Clones removed
==============
+ improver_tests/wind_calculations/wind_downscaling/test_RoughnessCorrection.py  -2
+ improver_tests/wxcode/wxcode/test_utilities.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6350585&bid=20622652)

2020-10-21 08:23 UTC, MoseleyS approved these changes

2020-10-21 08:23 UTC, merged