Updates code to prevent combine outputting float64 data
metoppv/improver pull request #1360
Opened 2020-11-02 09:11 UTC by MoseleyS

Updates code to prevent combine outputting float64 data which can happen if inputs are of mixed type. Specifically, multiplying float32 by int32 results in float64.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2020-11-02 11:45 UTC, BelligerG requested changes
This is a really good catch that currently is not tested in any acceptance or unit test.

Combining int32 with float32 results in a float64 due to the number of bits assigned to store the integer sections; in a float32 16 bits are used for the integer.  So in order not to reduce the precision, python puts out a float64 to keep the full 32 bits for the integer section.

We can combat this by using a smaller data type for the ints, after a conversation with @MoseleyS it appears that the ints are used for masks containing 0's and 1's. Therefore, my recommendation is not to fix this here, but to fix the root of the problem by changing data types in the mask generation to a boolean type (1 byte).

e.g. here:
https://github.com/metoppv/improver/blob/50620674a37ef92f83013435e796d7ec6258560c/improver/psychrometric_calculations/significant_phase_mask.py#L140
https://github.com/metoppv/improver/blob/50620674a37ef92f83013435e796d7ec6258560c/improver/psychrometric_calculations/precip_phase_probability.py#L180
https://github.com/metoppv/improver/blob/50620674a37ef92f83013435e796d7ec6258560c/improver/generate_ancillaries/generate_ancillary.py#L161

and anywhere else a mask is created.

By doing it this way we avoid an unnecessarily large intermediate structure as well as lowering our memory usage and our file sizes.

2020-11-02 13:41 UTC, bayliffe approved these changes

2020-11-02 13:43 UTC, bayliffe commented
Happy with this change, but if you want to adopt Chris's suggestion, that is also a good idea. I think we might still want a check here as we don't control all mask creation; this also allows you to make more immediate progress.

2020-11-03 08:29 UTC, benfitzpatrick commented on improver/cube_combiner.py
> +        if result.dtype in types_to_fix:
Could do e.g. `if result.dtype in FLOAT_TYPES and result.dtype != FLOAT_DTYPE`.

`FLOAT_DTYPE` maybe should be called something like `FLOAT_TYPE_OUTPUT` or `FLOAT_TYPE_DESIRED` if that's really what it is.

2020-11-03 12:35 UTC, MoseleyS commented
Adopting Chris' suggestion. New PR will replace this one.

2020-11-03 12:35 UTC, closed without merging