Unsafe night mask
metoppv/improver pull request #1370
Opened 2020-11-17 17:08 UTC by cgsandford

The apply-night-mask CLI was written and tested for use with UV values.  However we've needed to apply it in the suite to post-processed probabilities, to ensure night values aren't smoothed out by neighbourhood processing.  This PR adds additional checks for safe use of probabilities with this CLI.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2020-11-18 11:00 UTC, MoseleyS requested changes
The code change is fine, but the acceptance test data are much larger than the tests justify.

2020-11-19 08:34 UTC, cgsandford commented on improver_tests/acceptance/test_apply_night_mask.py
> +    args = [kgo_dir / "invalid_input.nc", "--output", output_path]
Ugh, sorry.  I generated the input file by thresholding the UK realizations input, but didn't collapse over realizations.  Would this be acceptable collapsed over realizations?

2020-11-19 09:39 UTC, cgsandford commented on improver_tests/acceptance/test_apply_night_mask.py
> +    args = [kgo_dir / "invalid_input.nc", "--output", output_path]
OK, I've now regenerated with 2 thresholds, collapsed realizations and a 300 x 300 domain crossing the day/night terminator.  Hopefully this is OK.

2020-11-19 14:29 UTC, MoseleyS approved these changes

2020-11-23 16:41 UTC, Kat-90 reviewed
Just a small thing.

2020-11-24 08:56 UTC, Kat-90 approved these changes
Run the tests and all is fine. Happy to approve this.

2020-11-24 11:23 UTC, merged