Shower probability
metoppv/improver pull request #1380
Opened 2020-12-01 16:16 UTC by cgsandford

New plugin to calculate shower probabilities based on cloud texture (for UK data) or cloud and convective fraction (for global).

Includes rearrangement of existing precipitation type modules without changes.  Thus the files that need review are:
- improver/precipitation_type/calculate_shower_prob.py
- improver_tests/precipitation_type/calculate_shower_prob/test_ShowerProbability.py

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2020-12-02 15:39 UTC, MoseleyS requested changes
My main comments are around the use of "shower probability". As you have spotted, the output isn't actually a probability field but a deterministic one, so I'd like to get rid of all the references to shower probability from the plugin.
There's also a hole in the plugin allowing a careless user to pass in data containing probabilities below the threshold instead of above and getting the exact opposite result of the one we want.

2020-12-02 15:39 UTC, MoseleyS commented on improver_tests/precipitation_type/calculate_shower_prob/test_ShowerProbability.py
> +        spatial_grid="equalarea",
If I add `spp__relative_to_threshold="below",` in here, or either of the other two set-up cubes, the tests still pass. I think the Plugin should be checking this and rejecting cubes with names that don't match "above".

2020-12-02 15:39 UTC, MoseleyS commented on improver/precipitation_type/calculate_shower_prob.py
> +                Binary (0/1) "probability of showery precipitation"
```suggestion
                Binary (0/1) "precipitation is showery"
```

2020-12-02 15:39 UTC, MoseleyS commented on improver/precipitation_type/calculate_shower_prob.py
> +        on input fields
```suggestion
        Determine the shower condition from global or UK data depending
        on input fields
```

2020-12-02 15:39 UTC, MoseleyS commented on improver/precipitation_type/calculate_shower_prob.py
> +        """Calculate deterministic "shower probability" field"""
```suggestion
    def _calculate_shower_condition(self, shape):
        """Calculate deterministic "precipitation is showery" field"""
```

2020-12-02 15:39 UTC, MoseleyS commented on improver/precipitation_type/calculate_shower_prob.py
> +    """Plugin to calculate probability of showery precipitation"""
As the output isn't a probability field, I suggest a different name.
```suggestion
class ShowerCondition(BasePlugin):
    """Plugin to calculate precipitation is showery condition"""
```

2020-12-02 15:39 UTC, MoseleyS commented on improver/precipitation_type/calculate_shower_prob.py
> +        shower_probability = np.ones(shape, dtype=FLOAT_DTYPE)
```suggestion
        showery_points = np.ones(shape, dtype=FLOAT_DTYPE)
```

2020-12-02 15:53 UTC, cgsandford commented on improver_tests/precipitation_type/calculate_shower_prob/test_ShowerProbability.py
> +    expected_data = [[0, 0, 0], [0, 0, 1], [1, 1, 1]]
Ugh sorry

2020-12-02 15:59 UTC, cgsandford commented on improver_tests/precipitation_type/calculate_shower_prob/test_ShowerProbability.py
> +        spatial_grid="equalarea",
Good point. I'll address the rest today and come back to this in the morning.

2020-12-02 16:00 UTC, cgsandford commented on improver/precipitation_type/calculate_shower_prob.py
> +        """Calculate deterministic "shower probability" field"""
Done.

2020-12-02 16:01 UTC, cgsandford commented on improver/precipitation_type/calculate_shower_prob.py
> +        shower_probability = np.ones(shape, dtype=FLOAT_DTYPE)
Done.

2020-12-02 16:02 UTC, cgsandford commented on improver_tests/precipitation_type/calculate_shower_prob/test_ShowerProbability.py
> +    assert result.shape == (3, 3)
OK.

2020-12-03 10:55 UTC, MoseleyS requested changes
Looking good. Just a couple of doc-strings that I think still need changing.

2020-12-03 10:55 UTC, MoseleyS commented on improver/precipitation_type/shower_condition.py
> +"""Plugin to calculate probability of showery precipitation"""
```suggestion
"""Plugin to calculate a precipitation is showery condition"""
```

2020-12-03 10:55 UTC, MoseleyS commented on improver/precipitation_type/shower_condition.py
> +    """Plugin to calculate precipitation is showery condition"""
Somewhere in the doc-strings, we need to describe what the conditions are that equate to showery. I suggest here, but it could be in the `process` method instead.

2020-12-03 11:31 UTC, cgsandford commented on improver/precipitation_type/shower_condition.py
> +    """Plugin to calculate precipitation is showery condition"""
I agree.  I've put this in `__init__` as that's where the dictionaries defining the conditions are described.

2020-12-03 11:36 UTC, cgsandford commented on improver/precipitation_type/shower_condition.py
> +"""Plugin to calculate probability of showery precipitation"""
OK

2020-12-03 13:43 UTC, MoseleyS approved these changes

2020-12-04 15:02 UTC, Katie-Howard approved these changes
I've looked through these changes, and most are just altering names, etc. The main changes are the extra plugin to check whether the precipitation will be showery or not and associated tests. 

These changes all seem very clear to me and well laid out. All the unit tests added look sensible, and they run through fine too. So I'm happy this does what it says. Good job 👍

2020-12-04 16:49 UTC, merged