Speed up PercentileBlendingAggregator (fixes #1215)
metoppv/improver pull request #1429
Opened 2021-03-12 07:27 UTC by btrotta-bom

Addresses #1215

Speed up `PercentileBlendingAggregator` using a more vectorised approach. This gives around a 5x speedup using the test script below. There is probably room for further improvement using numba.

I increased the tolerance in one of the tests slightly because it was failing, I think this is just a floating point issue since the calculation is essentially the same.

```
import numpy as np
import time
from improver.blending import weighted_blend

perc_values = np.random.rand(50, 10)
perc_values = np.sort(perc_values, axis=1)
percentiles = np.linspace(0, 1, 10)
weight = np.random.rand(50)

t = time.time()
ans = weighted_blend.PercentileBlendingAggregator.blend_percentiles(perc_values, percentiles, weight)
print(time.time() - t)

```

Testing:
 - [X] Ran tests and they passed OK

2021-03-12 11:32 UTC, cgsandford requested changes
Could you please have a look at the acceptance tests for weighted blending?  The two "percentile" tests are currently marked as "xfail" because they take so long to run.  With this new code, we should be able to re-activate those tests (or mark them as "slow" rather than "too slow to run").

If I run those percentile blending tests with your new code, they fail.  The error I get in both cases is: `ValueError: masked arrays are not supported`.

Could you investigate that please?

2021-03-15 02:35 UTC, btrotta-bom commented
I have rewritten the code to use `np.interp` instead of `scipy.interpolate`. This fixes the failing acceptance test and gives an even better speedup on my test script (now 17x). (Also I was able to restore the original tolerance in the unit test that I had previously increased.) The acceptance tests are faster now but not dramatically so (247s vs 318s to run all 20 tests in `test_weighted_blending`).

2021-03-15 09:05 UTC, cgsandford approved these changes
Thanks for this.  I've confirmed the acceptance tests run, and are a little faster in line with your measurements.

2021-03-17 00:00 UTC, benowen-bom approved these changes
Looks good to me. Associated tests ran and passed.

2021-03-17 00:01 UTC, merged