Removed use of upward uv flux and added new unit tests.
metoppv/improver pull request #1533
Opened 2021-08-12 13:05 UTC by Kat-90

Addresses #GitHubissuenum

Description:  
The upward UV flux has been removed from the UV_index calculation along with associated unit tests. Additional unit tests have been added to account for possible negative or NaN values within the input data.
Acceptance test data has been updated.
Related issue is linked to this PR: #1529 

Testing:
 - [X] Ran tests and they passed OK
 - [X] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

2021-08-13 10:33 UTC, MoseleyS requested changes
Hi Kat. 
Your changes look fine, but I've spotted a pre-existing spelling mistake.
Also, I'm surprised that there is no check that the units are in "W m-2" as the docstring requires. It isn't in the CLI either. The default scale factor requires the data to be in these units, so we ought to have a `uv_downward.convert_units("W m-2")` statement.
Also, the units of scale factor are not "no units", but the inverse of the UV data, so "m2 W-1".
Is it unreasonable to make changes to do this too? I know it is out of the original scope of the ticket.

2021-08-13 10:33 UTC, MoseleyS commented on improver/uv_index.py
>          Turner, E.C, Manners, J. Morcette, C. J, O'Hagan, J. B,
Not your fault, but please correct this spelling:
```suggestion
        Turner, E.C, Manners, J. Morcrette, C. J, O'Hagan, J. B,
```

2021-08-13 15:09 UTC, MoseleyS requested changes

2021-08-13 15:09 UTC, MoseleyS commented on improver/uv_index.py
> +        "ultraviolet_index", "W m-2", uv_downward, attributes, data=uv_data
No. The units for the UV index were correctly unitless. The point of the scale factor is that a UV index of 10 relates to a UV flux of 10/3.6 W m-2.

2021-08-16 10:34 UTC, MoseleyS submitted a review, later dismissed

2021-08-17 12:19 UTC, bayliffe requested changes
Looks good, a few tiny tweaks and suggestions.

2021-08-17 12:19 UTC, bayliffe commented on improver_tests/uv_index/test_uv_index.py
>          msg = "The radiation flux in UV downward"
This test actually needs a slightly longer expected, as there are two exceptions that both raise an error starting with "The radiation flux in UV downward", meaning this test cannot currently differentiate between them and check the correct exception has been triggered.

2021-08-17 12:19 UTC, bayliffe commented on improver_tests/uv_index/test_uv_index.py
> +            "that is negative or NaN. Data should be > 0."
```suggestion
            "that is negative or NaN. Data should be >= 0."
```

2021-08-17 12:19 UTC, bayliffe commented on improver_tests/uv_index/test_uv_index.py
> +        )
Or just:
```suggestion
        negative_uv_down = self.cube_uv_down.copy(data=negative_data_down)
```

2021-08-17 12:19 UTC, bayliffe commented on improver_tests/uv_index/test_uv_index.py
> +            "that is negative or NaN. Data should be > 0."
```suggestion
            "that is negative or NaN. Data should be >= 0."
```

2021-08-18 07:21 UTC, bayliffe commented on improver/uv_index.py
> +            referenced below.(m2 W-1)
Not quite what I meant, I was  more thinking:
```
        scale_factor:
            The uv scale factor. Default is 3.6 (m2 W-1). This factor has
            been empirically derived and should not be
            changed except if there are scientific reasons to
            do so. For more information see section 2.1.1 of the paper
            referenced below.
```

2021-08-18 07:29 UTC, Kat-90 commented on improver/uv_index.py
> +            referenced below.(m2 W-1)
Sorry, I see what you meant now. Done.

2021-08-18 07:36 UTC, bayliffe approved these changes

2021-08-18 07:36 UTC, merged