compare_coords function modified to accept ignored_coords list
metoppv/improver pull request #1535
Opened 2021-08-17 13:33 UTC by bayliffe

The compare_coords function now accepts an additional argument that takes the form of a list of coordinate names. This list is checked when cycling through the cubes to ensure that the presence / absence of a coordinate in this list from one or more cubes is not flagged as a difference. Differences in values for an ignored coordinate are also ignored.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2021-08-17 13:44 UTC, MoseleyS requested changes
This looks good, although I think the type-hinting can be more specific.

2021-08-17 13:44 UTC, MoseleyS commented on improver/utilities/cube_manipulation.py
> +def compare_coords(cubes: CubeList, ignored_coords: List = []) -> List[Dict]:
```suggestion
def compare_coords(cubes: CubeList, ignored_coords: List = [str]) -> List[Dict]:
```

2021-08-18 02:00 UTC, tjtg reviewed
This is good progress on a fix for #1534. It's different to the approaches I originally thought of in that issue, but discussion in that issue thread indicates that this is a good way to resolve the issue.
I'd be happy to approve once comments on `compare_coords` function get resolved.

2021-08-18 08:03 UTC, bayliffe commented
There I was thinking I would get away with the default argument as a list 😄. Changed as requested.

2021-08-18 08:47 UTC, tjtg approved these changes
All looks good now :+1:

2021-08-18 11:41 UTC, MoseleyS approved these changes

2021-08-18 14:12 UTC, merged