Modifies LightningFromCapePrecip plugin to accept 3h precipitation-rate-max data
metoppv/improver pull request #1568
Opened 2021-09-27 13:18 UTC by MoseleyS

Addresses #1518

We need this so we can generate data for days 6-8 when only 3h data are available.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2021-09-27 14:19 UTC, gavinevans requested changes
Thanks @MoseleyS 👍 

I've added a few minor comments.

2021-09-27 14:41 UTC, MoseleyS commented on improver/lightning.py
> +        that CAPE time is at the lower bound of precipitation rate time.
Fixed. Final tweak from #1550 hadn't been committed and merged - it has now.

2021-09-27 14:42 UTC, MoseleyS commented on improver_tests/lightning/test_LightningFromCapePrecip.py
> +    precip_cube.coord("time").bounds = (bounds[0][0], bounds[0][1] + 1)
Done

2021-09-27 14:43 UTC, MoseleyS commented on improver_tests/lightning/test_LightningFromCapePrecip.py
> +    bounds = precip_cube.coord("time").bounds
Good point. Done

2021-09-27 14:43 UTC, MoseleyS commented on improver_tests/lightning/test_LightningFromCapePrecip.py
> +def test_3d_cubes(cape_cube, precip_cube, expected_cube):
:-O   Fixed

2021-09-27 15:10 UTC, gavinevans requested changes

2021-09-27 15:10 UTC, gavinevans commented on improver_tests/lightning/test_LightningFromCapePrecip.py
> +
Black is currently failing and it's probably because of this blank line.

2021-09-27 15:23 UTC, gavinevans approved these changes

2021-09-28 09:43 UTC, bayliffe approved these changes
This looks fine, and all the tests pass. I've nothing to add.

2021-09-28 09:43 UTC, merged