Expanding on triangle time blending doc strings.
metoppv/improver pull request #1630
Opened 2021-12-15 08:41 UTC by Kat-90

Addresses #GitHubissuenum

Description:

The doc strings relating to the triangle time blending functionality had some errors in and needed updating so that they were consistent across the multiple related files.

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

2021-12-16 11:16 UTC, MoseleyS requested changes
Looks good, but here's a small suggestion.

2021-12-16 11:16 UTC, MoseleyS commented on improver/blending/blend_across_adjacent_points.py
> +    further they get until the specified width has been reached.
```suggestion
    Applies a weighted blend to the data using a triangular weighting function
    at each point in the specified dimension. The maximum weighting is applied
    to the specified point, and weighting decreases linearly for neighbouring
    points to zero at the specified triangle width.
```

2021-12-16 14:05 UTC, MoseleyS approved these changes

2021-12-16 14:14 UTC, bayliffe reviewed
Looks much better Kat, thanks. One teeny tiny comment.

2021-12-16 14:14 UTC, bayliffe commented on improver/blending/weights.py
> +                argument, which will determine the triangular weighting function
> The width from the triangle’s centre point, in units of the **_plugin's_** units argument, which will determine the triangular weighting function....


This function doesn't have a units argument, so it's probably worth pointing the reader up to the plugin level.

2021-12-17 08:34 UTC, bayliffe approved these changes

2021-12-17 08:34 UTC, merged