Weather code tree update
metoppv/improver pull request #1635
Opened 2021-12-23 10:53 UTC by MoseleyS

Addresses https://github.com/metoppv/mo-blue-team/issues/92

Following work on the issue above, I found that the weather code inputs needed updating. As the weather code decision trees have recently been changed to include hail and to work with precipitation accumulation data instead of rate, I chose to update the acceptance tests with the new decision trees and fresh data. The new acceptance test data are in branch `mobt_92_wxcode_tree_update`.

Testing:
 - [x] Ran tests and they passed OK

2022-01-05 12:39 UTC, gavinevans requested changes
Thanks for these amendments, @MoseleyS 👍 

I've added a query.

2022-01-05 12:39 UTC, gavinevans commented on improver_tests/acceptance/SHA256SUMS
> +5a3a808f0cc7952e6cc4225d09136276f685c5fdd6798a795c0430aa65ca71fa  ./wxcode/basic/kgo.nc
Just a couple of queries regarding these acceptance tests.

1. Based on [this comment](https://github.com/metoppv/mo-blue-team/issues/92#issue-1016463122), it seems like the intention is not to include "in_vicinity" within the cell method for the vicinity diagnostics. For the inputs to the weather symbols, it seems like they do not have "in_vicinity" in the cell method, which seems correct but ​`interpret-metadata`​ seems to think that they should. Will just behaviour of ​`interpret-metadata`​ be corrected, or has been corrected by one of your PRs e.g. https://github.com/metoppv/improver/pull/1632? 

2. ​`interpret-metadata`​ warns about the ​`mosg__model_run​` attribute, which is present on some but not all of the inputs. Should this attribute be present?

2022-01-05 17:14 UTC, gavinevans commented on improver_tests/acceptance/SHA256SUMS
> +5a3a808f0cc7952e6cc4225d09136276f685c5fdd6798a795c0430aa65ca71fa  ./wxcode/basic/kgo.nc
OK, I've now realised that the `mosg__model_run` attribute is potentially expected after model blending as model provenance information following https://github.com/metoppv/improver/pull/1569. The presence of the `mosg__model_run` attribute on these inputs is, therefore, fine.

2022-01-05 17:14 UTC, gavinevans approved these changes

2022-01-05 17:28 UTC, gavinevans commented on improver_tests/acceptance/SHA256SUMS
> +5a3a808f0cc7952e6cc4225d09136276f685c5fdd6798a795c0430aa65ca71fa  ./wxcode/basic/kgo.nc
Given that `mosg__model_run` is an accepted attribute, potentially `interpret_metadata` should be updated to reflect this.

2022-01-06 12:00 UTC, bayliffe commented
Plotted it all. Ran the tests. Happy.

2022-01-06 12:00 UTC, bayliffe approved these changes

2022-01-06 12:01 UTC, merged

2022-01-07 08:26 UTC, MoseleyS commented
Merged acceptance test data from `mobt_92_wxcode_tree_update`