Mobt 157 nbhood refactor tidy clis
metoppv/improver pull request #1679
Opened 2022-02-23 17:26 UTC by fionaRust

Patially Addresses https://github.com/metoppv/mo-blue-team/issues/157
Removes unnecessary options from CLIs and ensure full acceptance test coverage for the new useage

New acceptance test data on the ticket.

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

2022-02-28 12:08 UTC, bayliffe requested changes
A few comments, nothing major.

2022-02-28 12:08 UTC, bayliffe commented on improver_tests/acceptance/test_nbhood_land_and_sea.py
> +def test_basic_circular(tmp_path):
Same again, if not writing it in the doc-string, the test above needs a `_square` suffix.

2022-02-28 12:08 UTC, bayliffe commented on improver_tests/acceptance/test_nbhood_land_and_sea.py
> +def test_topographic_bands_probabilities_circular(tmp_path):
Here as well.

2022-02-28 14:04 UTC, fionaRust commented on improver/cli/nbhood_iterate_with_mask.py
> +            output.
Sorry too much copy and pasting.

2022-02-28 14:04 UTC, fionaRust commented on improver/cli/nbhood_land_and_sea.py
> +            output.
And again

2022-02-28 14:05 UTC, fionaRust commented on improver/cli/nbhood_iterate_with_mask.py
> -        remask (bool):
Removed

2022-02-28 14:08 UTC, fionaRust commented on improver/nbhood/use_nbhood.py
> -            re_mask:
Changed

2022-02-28 14:51 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood_iterate_with_mask.py
> +def test_collapse_bands_circular(tmp_path):
I think I've changed all of these now

2022-02-28 15:40 UTC, bayliffe approved these changes

2022-03-07 17:22 UTC, gavinevans requested changes
Thanks @fionaRust 👍 

@mspelman07 and I have added a few comments.

2022-03-08 14:59 UTC, fionaRust commented on improver/cli/nbhood_iterate_with_mask.py
> +    neighbourhood_shape,
Yep I missed this, now removed

2022-03-08 15:12 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood.py
> -        "--remask",
Yes it is, I've removed it and the corresponding KGO.

2022-03-08 15:20 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood_iterate_with_mask.py
> +@pytest.mark.slow
Done

2022-03-08 15:29 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood_land_and_sea.py
> +def test_basic_square(tmp_path):
Done

2022-03-08 15:29 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood_land_and_sea.py
> +def test_topographic_bands_probabilities_square(tmp_path):
Done

2022-03-08 16:58 UTC, gavinevans requested changes
Thanks @fionaRust 👍 

This looks good apart from some commented out code in the `test_nbhood_iterate_with_mask.py` file that should be removed.

2022-03-08 16:58 UTC, gavinevans commented on improver_tests/acceptance/test_nbhood_iterate_with_mask.py
> +# @pytest.mark.slow
I think that this can now be removed.

2022-03-09 13:42 UTC, fionaRust commented on improver_tests/acceptance/test_nbhood_iterate_with_mask.py
> +# @pytest.mark.slow
Done

2022-03-09 14:49 UTC, gavinevans approved these changes

2022-03-09 14:50 UTC, merged