Fix snow falling level nan/masked issue
metoppv/improver pull request #1722
Opened 2022-05-23 12:50 UTC by benfitzpatrick

We sometimes get NaNs passing through in falling level interpolation, even when horizontal interpolation is used.

This adds a fix to just interpolate without anything fancy when we get NaNs falling through the rest of the interpolation. It may just be for discussion and comment rather than going in as-is, but I think the work is useful either way.

As the method was getting a little long I split it out, but the actual substantive change is the block with the comment saying 'This should be rare'.

I've added unit tests that cover the behaviour, all of which except the peaked grid radius 2 case pass through NaNs and fail when the code change is commented out.

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

2022-05-24 13:00 UTC, benfitzpatrick commented
It's a little disturbing that the unit tests pass locally but fail here!

2022-05-25 12:53 UTC, MoseleyS requested changes
The failing tests need sorting out, as does the Black compliance.
Has our local conda pack for testing IMPROVER been updated recently?

2022-05-26 09:41 UTC, MoseleyS requested changes
I know you're still working on this, but I was curious.

2022-05-26 09:41 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        self.phase_change_data_1d = np.array([[1000.0, np.nan, 800.0]])
These arrays are all `float64`, they ought to be `float32` I think.

2022-05-26 09:41 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        """Test that we still fill in missing areas under a 1d peaked edge case."""
The word "still", in all these test doc-strings, is only appropriate for this PR. It probably ought to be removed for future clarity.

2022-05-26 09:41 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        """Set up input data."""
Perhaps this doc-string could just state the three cases being set up

2022-05-26 09:41 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        expected_result[2][3] = self.orography_2d[2][3]  # Why different from radius 1?
Increasing the grid point radius causes more source data points to be excluded from the interpolation, hence a different value comes out.

2022-05-27 09:00 UTC, cpelley submitted a review, later dismissed
Thanks Ben, nice range of unittests 👍

2022-06-06 15:13 UTC, MoseleyS commented
@benfitzpatrick: There are some outstanding comments from me on this PR.

2022-06-06 16:06 UTC, benfitzpatrick commented on improver/psychrometric_calculations/psychrometric_calculations.py
> +            )
Yes good point! I've raised https://github.com/metoppv/improver/issues/1736.

2022-06-07 08:23 UTC, cpelley approved these changes

2022-06-09 07:31 UTC, benfitzpatrick commented on envs/conda-forge.yml
> -  - scipy
@tjtg, 1.5.X or 1.6.X seem to work fine, 1.4.X produces a sphinx error. Suggesting pinning as <1.7?

2022-06-13 09:36 UTC, MoseleyS commented
I'm satisfied that the changes I requested have been done. I will leave this to @bayliffe to review now.

2022-06-14 15:28 UTC, bayliffe commented
## The problem

The problem we face is a pretty rare edge case in which the use of a neighbourhood to determine the max orography in neighbourhood is not sufficient to find valid data for use in interpolation.

The interpolation of the phase change level through orography relies on neighbouring points for which the phase change level is set AND at which this phase change level is below the maximum orography altitude in the neighbourhood (set to +- 1 grid point for ENGLUK in our fix).

The blue lines in the diagram below mark the maximum neighbourhood orography altitude at each point (the dashed vertical lines are indicating the grid spacing). In this edge case the phase change level is dipping to just clip the edge of the orography, with the intersection spanning only a single grid point. Moreover the gradient of the phase change level either side of this point is steeper than the gradient of the orography. Thus to either side we find the phase change level is above the local maximum orography altitude and thus not available to use for interpolation per our conditions.

![image](https://user-images.githubusercontent.com/28042362/173613850-0b6a183f-bc77-4bd4-b694-6fa639096747.png)

In this particular case we could fix the issue by increasing the neighbourhood radius by 1. That would extend the maximum orography in neighbourhood derived from the peak to the right by one more grid cell and thus we would get a phase change level to use as a nearest neighbour source. However the phase change level gradient need only be a bit steeper on the right hand side and this fix would not save us. As such this is going to need a bit more thought. I include the actual profile below (altitude is the vertical axis and grid point index along this particular row is the horizontal axis).

![broken](https://user-images.githubusercontent.com/28042362/173614183-92ae19bb-aa8c-4145-af7a-0dae62f9c00f.png)

## The interpolation fix

This PR implements a final nearest neighbour interpolation step without conditions for any unset points after all the other attempts have been made. The only points that should be unset upon reaching this step are those for which the phase change level is below the surface but which we have been unable to establish a sensible value for. Using this fix we get the phase change level shown below.

![bens_fix](https://user-images.githubusercontent.com/28042362/173614596-ee504913-e84c-437a-a081-a3f453dba5a2.png)

This does provide a continuous phase change level with no NaNs left in the domain. However, the result is counter to our foreknowledge that the phase change level must be below the surface (below the orography marked on the figure).

## Assumed surface level fix

An alternative to the approach proposed here would be to as a last resort for unset points use the orography as the altitude for the phase change level. Such a method is already employed in the last interpolation step that exists in the code prior to this change; it performs a horizontal interpolation (with conditions on the source points) but imposes the surface altitude as a limit if the interpolation results in any points above this altitude. We could implement this by either simply setting NaN points to the surface altitude in place of the proposed interpolation step, or we could apply limits to the extra interpolation step; both approaches give an identical result which is shown below.

![orog_fix](https://user-images.githubusercontent.com/28042362/173615979-d27cc1e1-d701-4084-9967-59f04d42224c.png)


## Conclusion

We should either apply limits to the interpolation step that has been added in this PR or replace it with a simple setting of points to orographic height. This would ensure that the resulting phase change level is at or below the surface altitude as we know it must be.

```
        if np.isnan(phase_change_data).any():
            # This should be rare.
            phase_change_data = interpolate_missing_data(
                phase_change_data, method="nearest", limit=orography,
            )
```

or

```
        if np.isnan(phase_change_data).any():
            index = ~np.isfinite(phase_change_data)
            phase_change_data[index] = orography[index]
```

2022-06-16 16:30 UTC, bayliffe commented
I've raised a PR to this PR to implement the orography limit change so we can get this merged and fix the midnight tests. If you are happy Ben, please merge this into your branch.

https://github.com/benfitzpatrick/improver/pull/5

2022-06-17 07:55 UTC, bayliffe approved these changes

2022-06-17 07:58 UTC, merged

2022-06-17 09:03 UTC, cpelley commented
Awesome illustration @bayliffe!