Add vertical updraught CLI and plugin
metoppv/improver pull request #1729
Opened 2022-05-30 12:03 UTC by MoseleyS

Closes #1727

Adds `vertical-updraught` CLI and `VerticalUpdraught` plugin to calculate the maximum vertical updraught from CAPE and maximum precipitation. This will be part of a chain to calculate hail from a model that does not output hail directly.

Acceptance test data are in a branch named `mobt1727_vertical_updraught`

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-06-14 15:49 UTC, mspelman07 requested changes
A few requests for clarification but nothing very big.

2022-06-15 08:20 UTC, MoseleyS commented on improver/wind_calculations/vertical_updraught.py
> +            (self.cape, self.precip) = cubes.extract(self.cube_names)
As I understand it, the important bit is the order of the list of strings `self.cube_names`. The output cubes will be in the same order as this, so it shouldn't matter if `cubes` is in the reverse order (but I agree it needs a test). I intend the method to work regardless of the input cube order.

2022-06-15 08:22 UTC, MoseleyS commented on improver/wind_calculations/vertical_updraught.py
> +        self.cape.convert_units("J kg-1")
Iris raises a useful `ValueError` in this case, which is captured in the error-checking unit-test.

2022-06-15 09:51 UTC, MoseleyS commented on improver/wind_calculations/vertical_updraught.py
> +        """
Good spot. doc-string updated

2022-06-15 09:51 UTC, MoseleyS commented on improver/wind_calculations/vertical_updraught.py
> +        updraught[self.cape.data < 10] = 0.0
Added. I've also moved 10 and 5 to be `self._minimum_cape` and `self._minimum_precip` to make them a bit clearer.

2022-06-15 09:51 UTC, MoseleyS commented on improver_tests/wind_calculations/vertical_updraught/test_VerticalUpdraught.py
> +        ),
Tests for these cases added.

2022-06-16 14:47 UTC, mspelman07 submitted a review, later dismissed

2022-06-17 10:42 UTC, MoseleyS commented on improver/wind_calculations/vertical_updraught.py
> +    """
Yes, I think you're right. I've now changed the plugin class inheritance and updated the test results accordingly.

2022-06-20 13:01 UTC, MoseleyS commented on improver_tests/wind_calculations/vertical_updraught/test_VerticalUpdraught.py
> +def cape_has_time_bounds(cubes: List[Cube]):
Good spot. Added - I've also changed the other error messages to say "must" instead of "should".

2022-06-20 13:28 UTC, merged

2022-06-20 13:29 UTC, MoseleyS commented
Merged acceptance test data