Adding hail phase changes and associated tests
metoppv/improver pull request #1762
Opened 2022-07-12 10:27 UTC by mspelman07

Addresses #1743

Description

Updates plugins to calculate the hail melt mask.

Acceptance test data on brach `mobt1743_hail_melt_level`

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-07-12 13:01 UTC, MoseleyS requested changes
Looks good! I think I only found a few stray print statements to delete.

2022-07-12 14:54 UTC, mspelman07 commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        print(result.data)
Done

2022-07-12 14:54 UTC, mspelman07 commented on improver_tests/psychrometric_calculations/precip_phase_probability/test_PrecipPhaseProbability.py
> +        print(expected)
Done

2022-07-12 14:54 UTC, mspelman07 commented on improver_tests/acceptance/test_phase_change_level.py
> +    print(kgo_path)
Done

2022-07-12 14:54 UTC, mspelman07 commented on improver/psychrometric_calculations/precip_phase_probability.py
> +        print(cubes)
Done

2022-07-12 15:26 UTC, MoseleyS submitted a review, later dismissed

2022-07-18 07:12 UTC, Kat-90 requested changes
This looks great. I've reviewed the code and asked for a couple minor changes, pulled the branch and run both unit tests and acceptance data. All looks fine. Happy to approve once those changes have been addressed. Thanks

2022-07-18 08:56 UTC, mspelman07 commented on improver/psychrometric_calculations/precip_phase_probability.py
> +        supplied, this is the probability of rain from hail at (or above) the surface.
Done

2022-07-18 08:56 UTC, mspelman07 commented on improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
> +        for the sleet_rain phase change."""
Done

2022-07-18 10:21 UTC, Kat-90 approved these changes
Thanks for the changes, happy to approve.

2022-07-18 10:29 UTC, merged