Implement input cube check functions - Stage 1: Feels like temperature
metoppv/improver pull request #1782
Opened 2022-08-02 14:54 UTC by Kat-90

This PR adds functionality to the feels like temperature CLI to be able to pass input cubes in any order.
It also adds input cube functions to the feels like temperature plugin in order to check spatial and temporal coords match.

This PR acts as a first step toward a bigger issue: #1770 and more PR's will be put up as plugins/CLI's are changed.

Addresses #GitHubissuenum

Description

Testing:
 - [X] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

2022-08-02 15:35 UTC, gavinevans reviewed
Thanks @Kat-90 👍 

I think that these changes look correct. I think in this instance, you don't need to make use of `get_model_id_attr`, as you've done, as `generate_mandatory_attributes` is already doing the desired attribute check. 

There is one [mailmap](https://github.com/metoppv/improver/runs/7634244432?check_suite_focus=true#step:3:93) error that has occurred. Let's have a quick chat about this.

2022-08-04 12:39 UTC, gavinevans requested changes
Thanks @Kat-90 👍 

I've added a couple of comments.

2022-08-04 12:39 UTC, gavinevans commented on improver/cli/wind_gust_diagnostic.py
> +    return WindGustDiagnostic(wind_gust_percentile, wind_speed_percentile)(
I think that the WindGustDiagnostic plugin could also be updated with the usage of the    `assert_spatial_coords_match` and `assert_time_coords_valid` functions. I can see that this plugin is already comparing whether the time coordinates are valid on [these lines](https://github.com/metoppv/improver/blob/master/improver/wind_calculations/wind_gust_diagnostic.py#L185-L202) by checking whether the wind speed time point is within the time bounds provided by the wind gust cube. This kind of check isn't supported by `assert_time_coords_valid` but we could consider whether `assert_time_coords_valid` could be updated to support this kind of check.

2022-08-05 10:15 UTC, Kat-90 commented
NB: I have left out the assert_time_coords function from wind_gust_diagnostic.py as this plugin takes one cube with time points (wind_speed) and one cube with time bounds (wind_gust).

2022-11-23 01:43 UTC, closed without merging