MOBT-334: Day/Night calculation using bounds for time bounded variables
metoppv/improver pull request #1786
Opened 2022-08-11 12:30 UTC by bayliffe

## What it does
Modifies the day/night terminator calculation to use time bounds mid-point for diagnostics with time bounds.

If the input cube's time coordinate has time bounds the mid-point of these bounds, rather than the time point, is now used in the calculation of the day/night status of the data. This ensures that should a majority of the period described fall into daylight hours, the data is not classified as falling at night. This is an issue as the time point is always located at the end of the time bounds. Without this approach e.g. weather symbols representing e.g. 20-21Z will be marked as night symbols should the sunset at 20:59 which is not suitable.

## Impacts
This PR includes one change the acceptance test data which is for the global weather symbols (3-hour). The annotated figure below shows the data that has changed.

Where they exist, night codes are one lower than their daytime equivalents. The figure shows that all the changes are +- 1 and around the terminator. The red section shows locations that have been reclassified as day symbols following the change (+1). This is because the terminator has been shifted east from the 21Z location to the midpoint of the bounds (18-21Z), it's location at 19:30Z. Points west of this are forecasting for a period that is more day than night.

![labelled_terminator_shift](https://user-images.githubusercontent.com/28042362/184132069-a060e1e6-c2f2-4cb6-abd4-99eaa0fa66b4.jpg)

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-08-16 14:18 UTC, mspelman07 requested changes
A couple of small changes.

2022-08-16 15:22 UTC, bayliffe commented on improver/utilities/solar.py
> +                dtval = lb + (ub - lb) / 2
Yep, but you can't do that with datetime objects. They can't be added as it is meaningless to add two dates. However, you can subtract them to get the time difference between them and you can add a time difference to a date to get a new date, hence the slightly convoluted form above.

2022-08-17 14:25 UTC, mspelman07 submitted a review, later dismissed

2022-08-22 15:20 UTC, bayliffe commented on improver/utilities/solar.py
> +        e.g. 20-21Z will be marked as night symbols should the sunset at
I meant this to be "sun set" but lost a space along the way. I've added it back,

2022-08-22 15:21 UTC, bayliffe commented on improver_tests/wxcode/wxcode/test_WeatherSymbols.py
> +        twelve_hours = 3600 * 12
Done.

2022-08-23 07:42 UTC, gavinevans approved these changes

2022-08-23 07:43 UTC, merged