MOBT-272: Reduce memory usages in freezing-rain calculation
metoppv/improver pull request #1788
Opened 2022-08-15 11:51 UTC by bayliffe

Modifies calculation of freezing-rain such that realization collapse occurs within the plugin.

The realization collapse is now performed (assuming an equal weight for each realization) by summing the freezing rain probability from each realization slice weighted by 1/n_realizations. This removes the need to hold all of the realizations in memory at the same time to perform the averaging calculation. It also removes the need for a realization_collapse step in the suite.

Memory usage is reduced by a factor of ~8 and the need for a separate realization collapse step is removed.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)
 - [x] There is demonstration of the memory improvements on the [associated ticket](https://github.com/metoppv/mo-blue-team/issues/272) and testing that results remain unchanged using real-data.

2022-08-16 09:52 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've added some minor docstring comments.

2022-08-16 12:42 UTC, bayliffe commented on improver/precipitation_type/freezing_rain.py
> +    def _calculate_freezing_rain_probability(self, n_realizations) -> Cube:
Done.

2022-08-16 12:42 UTC, bayliffe commented on improver/precipitation_type/freezing_rain.py
> +    def _generate_template_cube(self, n_realizations):
Done.

2022-08-16 12:43 UTC, bayliffe commented on improver/precipitation_type/freezing_rain.py
> +        """
Done.

2022-08-16 12:51 UTC, bayliffe commented on improver/precipitation_type/freezing_rain.py
> +            template = next(self.sleet.slices_over("realization")).copy()
Justification added.

2022-08-16 12:53 UTC, bayliffe commented on improver/precipitation_type/freezing_rain.py
> +        diagnostic. Collapses the realization coordinate.
Done.

2022-08-16 14:30 UTC, gavinevans commented on improver/precipitation_type/freezing_rain.py
> +            template = next(self.sleet.slices_over("realization")).copy()
Thanks, that's useful.

2022-08-16 14:50 UTC, gavinevans approved these changes

2022-08-23 09:18 UTC, mspelman07 approved these changes

2022-08-23 10:14 UTC, merged