MOBT-353: Spot-extract uses resample percentiles to produce unavailable percentiles
metoppv/improver pull request #1796
Opened 2022-08-30 16:03 UTC by bayliffe

Modifies the spot-extract CLI to use ResamplePercentiles when necessary. This is required when spot-extracting percentile output from gridded percentile inputs that do not contain the target percentiles.

Previously the CLI extracted as much as it could and only raised an exception if no data was available. Following this PR the CLI will instead check if the desired percentiles are available within the gridded data and perform a simple extraction if they are. If not it will resample the percentiles to generate the target set. No exception is now raised as the target percentiles can always be produced (with no doubt variable quality if the input percentile set is insufficient).

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-08-31 07:34 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've added one docstring comment and a query.

2022-08-31 10:18 UTC, bayliffe commented on improver/cli/spot_extract.py
> +        extract_percentiles = sorted([np.float32(x) for x in extract_percentiles])
It's legacy now and could be removed. When I modified the code to raise an exception if less than all of the requested percentiles were returned I did so using the length of the returned percentile coordinate. You suggests comparing the values themselves, which I did. However, whilst the user can specify percentiles in any order they like, the returned cube coordinate will be monotonically increasing. Therefore to compare the arrays simply I sorted the requested percentiles as well; see [this commit](https://github.com/metoppv/improver/pull/1796/commits/5c5ba8f23ad05126eb7635e44a779d6acf0fb3d9).

As we are no longer performing this check the test and sorting have no real value. Still, I might leave the disordered test just to demonstrate that the user specified order is irrelevant. I'll remove the `sorted` statement from the code as it is not needed.

2022-08-31 10:23 UTC, bayliffe commented on improver/cli/spot_extract.py
> +        ResamplePercentiles,
Done.

2022-08-31 13:25 UTC, gavinevans submitted a review, later dismissed

2022-09-08 13:47 UTC, mspelman07 requested changes
One small comment about a doc string.

2022-09-16 08:03 UTC, bayliffe commented on improver/cli/spot_extract.py
> +        ResamplePercentiles,
Good spot. Removed.

2022-09-16 13:49 UTC, mspelman07 approved these changes

2022-09-16 14:12 UTC, merged