Add function and test for flattening an arbitrarily nested iterable
metoppv/improver pull request #1801
Opened 2022-09-12 15:37 UTC by gavinevans

Description
This PR adds a function with tests for flattening an arbitrarily nested list. This is intended to help when the argument to a CLI is provided as a list, which is a mixture of individual cubes and cubelists, such as in #1792. The `flatten` function in this PR would help with flattening this nested list.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-09-16 12:23 UTC, mspelman07 requested changes
Looks good to me with one small query.

2022-09-20 07:39 UTC, gavinevans commented on improver/utilities/flatten.py
> +    for item in an_iterable:
For simplicity, I've modified this function to return a list.

2022-09-21 12:30 UTC, mspelman07 submitted a review, later dismissed

2022-09-21 13:18 UTC, MoseleyS requested changes
The stated objective of this PR is to flatten a list of lists into an unnested list. Why do we want to expand strings into a list of letters?

I've reworked the code to do this, and to reject other types. Since a CubeList of a sub-type of list, the method `isinstance(CubeList(), list)` returns `True`. I recommend adding objects of CubeList type to your unit tests too.

2022-09-21 13:19 UTC, MoseleyS requested changes
I forgot the actual code suggestion!

2022-09-21 13:19 UTC, MoseleyS commented on improver/utilities/flatten.py
> +    return alist
```suggestion
from typing import List, Union, Tuple


def flatten(nested_list: Union[List, Tuple]) -> List:
    """Flatten an arbitrarily nested iterable.

    Args:
        nested_list:
            An arbitrarily nested iterable to be flattened.

    Returns:
        A list containing a flattened version of the arbitrarily nested input.
    """
    flat_list = []
    if not isinstance(nested_list, (list, tuple)):
        raise ValueError(f"Expected object of type list or tuple, not {type(nested_list)}")
    for item in nested_list:
        if isinstance(item, (list, tuple)):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list
```

2022-09-22 09:57 UTC, MoseleyS approved these changes

2022-09-22 09:57 UTC, merged