MOBT-370: Cell method record of input wx period in modal symbols
metoppv/improver pull request #1815
Opened 2022-10-04 14:54 UTC by bayliffe

Addresses https://github.com/metoppv/mo-blue-team/issues/370

When calculating a modal weather symbol, this change ensures that the period of the input weather symbols is recorded in the cell method of the output modal symbol diagnostic. This differentiates products based on different input interval data using internal metadata rather than relying on the file name.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2022-10-05 11:05 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've added a couple of minor comments.

2022-10-05 13:39 UTC, gavinevans approved these changes

2022-10-17 12:40 UTC, MoseleyS requested changes
Just one thing

2022-10-17 12:40 UTC, MoseleyS commented on improver/wxcode/modal_code.py
> +            )
The Metadata Interpreter doesn't recognise these new cell methods. Please can you modify it so that these are acceptable.

2022-10-18 08:10 UTC, bayliffe commented on improver/developer_tools/metadata_interpreter.py
> +                            self.methods += f"{cm.method} of {cm.intervals[0]} {diagnostic} over {cm.coord_names[0]}"
Shortened.

2022-10-18 13:55 UTC, MoseleyS approved these changes

2022-10-18 14:52 UTC, merged