Speeds up the cloud-top-temperature CLI
metoppv/improver pull request #1824
Opened 2022-10-12 15:58 UTC by MoseleyS

Uses the existing mask to determine which columns need further processing. This thins the data more and more as the columns are ascended and results in a 3x speed-up for the MOGREPS-G global domain.

Testing:
 - [x] Ran tests and they passed OK

2022-10-13 08:45 UTC, mspelman07 submitted a review, later dismissed
All looks good.

2022-10-13 08:55 UTC, Kat-90 commented
I have tested this change in the suite which succeeds with a wallclock resource of 560S.

2022-10-13 16:02 UTC, gavinevans requested changes
Thanks for the update, @MoseleyS 👍 

I've made a few comments, mainly aimed at making the added code a bit clearer.

2022-10-14 09:31 UTC, MoseleyS commented on improver/psychrometric_calculations/cloud_top_temperature.py
> +        )
I tried that as part of this work. The issue with it is that `ccl_with_mask.mask` becomes a scalar value of `False`, and doesn't interact with the stuff below. My code generates a multi-dimensional mask instead.

2022-10-14 09:52 UTC, MoseleyS commented on improver/psychrometric_calculations/cloud_top_temperature.py
> +                (t_2_full < t_loc_full) & (p < self.p_at_ccl.data), ccl_with_mask,
You might be right, but this looks much more complex to me, so I have left this bit as it is.

2022-10-14 09:52 UTC, MoseleyS commented on improver/psychrometric_calculations/cloud_top_temperature.py
> +            t_dry = dry_adiabatic_temperature(
Now named `pressure`

2022-10-14 11:38 UTC, MoseleyS commented on improver/psychrometric_calculations/cloud_top_temperature.py
> +            t_loc = t.data[~ccl_with_mask.mask]
I've gone with t_environment. I've also changed t_2 to t_parcel, and t_dry to t_dry_parcel.

2022-10-14 11:47 UTC, MoseleyS commented on improver/psychrometric_calculations/cloud_top_temperature.py
> +            t_loc = t.data[~ccl_with_mask.mask]
Hmm - this seems to work, so I've put it in. Thanks.

2022-10-14 13:53 UTC, MoseleyS commented
I'm passing this back to Gavin, but I haven't been able to reassure myself that these latest changes still deliver the speed-up I had achieved, mostly because I can't remember exactly what test I ran. I need to check this again before this can be merged.

2022-10-14 14:28 UTC, gavinevans approved these changes

2022-10-17 08:31 UTC, MoseleyS commented
Finally worked out what I'd got wrong with my test - all is well. This can now be merged.

2022-10-17 08:31 UTC, merged