Removing ManageWarnings within the code and unit tests that use this.
metoppv/improver pull request #1864
Opened 2023-02-02 12:04 UTC by Katie-Howard

Addresses #GitHubissuenum

Description

Testing:
 - [x] Ran tests and they passed OK

2023-02-06 14:16 UTC, bayliffe commented on improver_tests/blending/calculate_weights_and_blend/test_WeightAndBlend.py
> -        self.assertTrue(any(message in str(item) for item in warning_list))
Added back using pytest.warns.

2023-02-06 14:27 UTC, bayliffe commented on improver_tests/blending/weighted_blend/test_MergeCubesForWeightedBlending.py
> -        self.assertIsNone(plugin.model_id_attr)
Added back using pytest.warns.

2023-02-06 14:42 UTC, bayliffe commented on improver_tests/calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
> -        self.assertTrue(any(warning_msg_iter in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 14:46 UTC, bayliffe commented on improver_tests/calibration/ensemble_calibration/test_ContinuousRankedProbabilityScoreMinimisers.py
> -        self.assertTrue(any(warning_msg_iter in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 15:26 UTC, bayliffe commented on improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns.

2023-02-06 15:31 UTC, bayliffe commented on improver_tests/calibration/reliability_calibration/test_ApplyReliabilityCalibration.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back with pytest.warns

2023-02-06 15:37 UTC, bayliffe commented on improver_tests/ensemble_copula_coupling/test_ConvertProbabilitiesToPercentiles.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 15:37 UTC, bayliffe commented on improver_tests/ensemble_copula_coupling/test_ConvertProbabilitiesToPercentiles.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 15:42 UTC, bayliffe commented on improver_tests/generate_ancillaries/test_GenerateTopographicZoneWeights.py
> -        self.assertTrue(any(msg in str(item) for item in warning_list))
Added back using pytest.warns.

2023-02-06 15:48 UTC, bayliffe commented on improver_tests/metadata/test_forecast_times.py
> -        self.assertEqual(result.points, [-3600])
Added back using pytests.warn
Removed duplicate calculation of result.

2023-02-06 15:49 UTC, bayliffe commented on improver_tests/nbhood/recursive_filter/test_RecursiveFilter.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 16:08 UTC, bayliffe commented on improver_tests/nowcasting/optical_flow/test_OpticalFlow.py
> -        self.assertTrue(len(warning_list) == 0)
Added back in using following syntax:
```
        with warnings.catch_warnings():
            warnings.simplefilter(action="error", category=UserWarning)
```
Such that an error is raised if a UserWarning is raised and the test fails.

2023-02-06 16:21 UTC, bayliffe commented on improver_tests/spotdata/test_NeighbourSelection.py
> -        self.assertTrue(any(item.category == UserWarning for item in warning_list))
Added back using pytest.warns

2023-02-06 16:23 UTC, bayliffe commented on improver_tests/utilities/cube_manipulation/test_compare_attributes.py
> -        self.assertArrayEqual(result, [])
Added back using pytest.warns

2023-02-06 16:25 UTC, bayliffe commented on improver_tests/utilities/cube_manipulation/test_compare_coords.py
> -        self.assertEqual(result, [])
Added back using pytest.warns

2023-02-06 16:26 UTC, bayliffe commented on improver_tests/utilities/cube_manipulation/test_sort_coord_in_cube.py
> -        self.assertIsInstance(result, iris.cube.Cube)
Added back using pytest.warns

2023-02-06 16:28 UTC, bayliffe commented on improver_tests/utilities/temporal/test_temporal.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 16:30 UTC, bayliffe commented on improver_tests/utilities/test_InterpolateUsingDifference.py
> -        self.assertTrue(any(warning_msg in str(item) for item in warning_list))
Added back using pytest.warns

2023-02-06 16:32 UTC, bayliffe commented on improver_tests/wind_calculations/wind_gust_diagnostic/test_WindGustDiagnostic.py
> -        self.assertIsInstance(perc_coord, iris.coords.Coord)
Added back using pytest.warns

2023-02-06 16:54 UTC, bayliffe submitted a review, later dismissed
I've reviewed this in as much as I have checked the removals are as expected. I have reintroduced tests that were removed erroneously, and I have fixed formatting errors. This needs a thorough second review in light of the changes I have made.

2023-02-07 14:40 UTC, MoseleyS requested changes
Looks very good. Spotted a couple of things to fix.

2023-02-07 14:40 UTC, MoseleyS commented on improver_tests/nowcasting/optical_flow/test_OpticalFlow.py
> +            _, _ = self.plugin.process(self.cube1, self.cube2, boxsize=3)
You've done this exactly as it was before, but it should be simplified to:
```suggestion
            self.plugin.process(self.cube1, self.cube2, boxsize=3)
```

2023-02-07 14:40 UTC, MoseleyS commented on improver_tests/regrid/test_AdjustLandSeaPoints.py
>  IGNORED_MESSAGES = ["Using a non-tuple sequence for multidimensional indexing"]
`IGNORED_MESSAGES` and `WARNING_TYPES` are no longer used and need to be deleted.

2023-02-08 15:20 UTC, MoseleyS approved these changes

2023-02-08 15:43 UTC, merged