Shrink acceptance test data - PR9
metoppv/improver pull request #1872
Opened 2023-02-17 10:08 UTC by bayliffe

A component of https://github.com/metoppv/improver/issues/1804

To reduce the data volume of the acceptance test data repository, work has been done to coarsen the resolution of test data relating to the following CLIs:

- spot-extract
- neighbour-finding

This PR updates the checksums and removes a redundant test for spot-extract. It also corrects a doc-string.

The relevant acceptance test data can be found in branch shrink_atd_9
Plotting of the original and modified data [can be seen here](https://github.com/MetOffice/improver_aux/blob/acceptance_test_data_shrinking/notebooks/acceptance_test_data/shrink_atd_9.ipynb).

2023-02-21 11:21 UTC, brhooper requested changes
For the most part, this seems fine, however the following 4 files seem to contain the same data now:

neighbour-finding/outputs/nearest_global_kgo.nc
neighbour-finding/outputs/nearest_land_constraint_minimum_dz_global_kgo.nc
neighbour-finding/outputs/nearest_land_global_kgo.nc
neighbour-finding/outputs/nearest_minimum_dz_global_kgo.nc

which was not the case previously. I don't think that this is expected behaviour as each kgo should be testing different functionality. The sites don't seem to have been changed much, if at all, so I assume that this is caused by the coarser resolution of the inputs.

2023-03-01 13:35 UTC, bayliffe commented
@brhooper you should now find that the data are different in all of the KGO. I have significantly increased the search radius for the nearest land or similar altitude neighbour to achieve this for the global data on the coarse grid. The figure below, covering some of South America, shows sites (circles) and the chosen neighbouring grid points (triangles) that correspond to different options (e.g. nearest, nearest-land, etc); sites and associated neighbours share the same colours.


![spot_options](https://user-images.githubusercontent.com/28042362/222153842-18cd8ac1-87f8-49c2-bcc9-5a95bd39f97c.png)

2023-03-01 14:14 UTC, brhooper approved these changes
Thanks for making those changes @bayliffe, this all looks fine now.

2023-03-01 15:54 UTC, MoseleyS commented
@bayliffe: Please can you resolve the conflicts on this PR?

2023-03-01 16:25 UTC, MoseleyS requested changes
I've spotted one test that doesn't have any non-zero data in it, so I'm requesting that it is changed. Otherwise, these changes look good.

2023-03-01 16:25 UTC, MoseleyS commented on improver_tests/acceptance/SHA256SUMS
> +23007b89be636fb0e7445f239a30fc9debf530fc19e33599a09226ec31625e7e  ./spot-extract/outputs/with_realization_collapse.nc
This output file contains only zeroes. So did the previous version. Basically, it isn't raining in the source data. Can you replace the source data so this task does something meaningful?

2023-03-06 14:02 UTC, bayliffe commented on improver_tests/acceptance/SHA256SUMS
> +a71031207447765f56f1c6a1d03342bfbd4363f4f170d191eb690c54d3fe8082  ./spot-extract/inputs/enukx_preciprate_realizations_thresholds.nc
Renamed `precipacc` after recreating it with more accumulation data.

2023-03-14 16:09 UTC, MoseleyS approved these changes
Looks better now. Assigning to Ben to resolve the conflicts before merging.

2023-03-20 16:08 UTC, MoseleyS approved these changes

2023-03-20 16:09 UTC, merged