Refactors SpotLapseRateAdjust so that the two pathways are easier to follow.
metoppv/improver pull request #1880
Opened 2023-02-24 14:39 UTC by MoseleyS

Following https://github.com/metoppv/improver/pull/1879, I want to refactor this code so that it is easier to see what is going on.

Testing:
 - [x] Ran tests and they passed OK

2023-03-21 08:19 UTC, bayliffe requested changes
Thanks, this looks better. Only a tiny comment to address.

2023-03-21 08:19 UTC, bayliffe commented on improver/spotdata/apply_lapse_rate.py
> +        Raises:
Can you move the Raises sections to the `_check_inputs` doc string.

2023-03-21 15:00 UTC, bayliffe submitted a review, later dismissed

2023-03-24 09:18 UTC, MoseleyS commented on improver/spotdata/apply_lapse_rate.py
> +        self, gridded_lapse_rate_cube: Cube, neighbour_cube: Cube, spot_data_cube: Cube
Done

2023-03-24 09:18 UTC, MoseleyS commented on improver/spotdata/apply_lapse_rate.py
> +        gridded_lapse_rate_cube: Cube = None,
I keep forgetting this. Added.

2023-03-24 15:36 UTC, gavinevans approved these changes

2023-03-24 15:37 UTC, merged