Add CLI to perform blending with mismatching vicinities and the option to rename the cube
metoppv/improver pull request #1895
Opened 2023-04-18 09:36 UTC by MoseleyS

Part of https://github.com/MetOffice/improver_suite/issues/1610

To achieve the meta-data changes requested here (https://github.com/MetOffice/improver_suite/pull/1611#discussion_r1165375538), I have created a new CLI to call `weighted-blending`, then modify the meta-data of the resulting cube before it is returned.

The metadata changes are:
- File name: `f"precipitation_accumulation_in_variable_vicinity-PT{period:02d}H"`
- Cube name: `probability_of_lwe_thickness_of_precipitation_amount_in_variable_vicinity_above_threshold`
- Cube coordinate: `radius_of_vicinity`, Value: 10000 m, With the addition of this comment attribute in the nowcast period only: `comment: "Maximum"`

Implementing this required these changes to allow me to reuse existing code:
- Refactors `update_diagnostic_name` and `_update_cell_methods` from `cube_combiner.CubeMultiplier` to `metadata.amend.py`
- Refactors `add_vicinity_coordinate` from `spatial.OccurrenceWithinVicinity` plugin to `spatial.py`
- New unit tests for these refactored methods.
- Modification to allow the `interpret-metadata` CLI to accept the new metadata.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-05-03 13:44 UTC, brhooper requested changes
Thanks @MoseleyS, I think this is mostly fine.

The only comments I've made are related to code style. I think I recall being told that there was a restriction of having up to 88 characters per line, though I can't seem to find a source for this now. If this is not the case then feel free to ignore my comments and I'll approve the PR.

2023-05-03 13:44 UTC, brhooper commented on improver/cli/blend_with_vicinity_and_rename.py
> +    """Runs weighted blending, with additional options to handle mismatched in_vicinity coords
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/cli/blend_with_vicinity_and_rename.py
> +            "Neither new_name nor vicinity_radius have been specified. Use weighted-blending "
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/metadata/amend.py
> +        source_cube: An original cube before any processing took place. Can be the same cube as
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/metadata/probabilistic.py
> +        "(?P<vicinity>_in_vicinity|_in_variable_vicinity)?"  # optional group, may be empty
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/utilities/spatial.py
> +    Updates a cube with a new probabilistic-style name and replaces or adds a radius_of_vicinity
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/utilities/spatial.py
> +        new_name: The new name to be applied to the Cube, the threshold coord and any related
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/utilities/spatial.py
> +        vicinity_radius: The point value for the radius_of_vicinity coord. The units are assumed
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/utilities/spatial.py
> +        # The cube blending will drop the radius_of_vicinity coord if the source cubes have
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver/utilities/spatial.py
> +            True if the specified radius represents a maximum value from the source data. A
This line might be too long.

2023-05-03 13:44 UTC, brhooper commented on improver_tests/metadata/test_amend.py
> +    """Make sure that the update_diagnostic_name method makes the expected changes in the expected
This docstring might have lines which are too long.

2023-05-04 08:17 UTC, MoseleyS commented
> Thanks @MoseleyS, I think this is mostly fine.
> 
> The only comments I've made are related to code style. I think I recall being told that there was a restriction of having up to 88 characters per line, though I can't seem to find a source for this now. If this is not the case then feel free to ignore my comments and I'll approve the PR.

Flake8 currently enforces a line-limit of 100 characters, so I tend to go with that. We've had different limits in the past. I know that there are other lines in our code base that are between 88 and 100 characters, so I don't think we need worry about this.

2023-05-04 08:21 UTC, brhooper approved these changes

2023-05-05 13:48 UTC, Katie-Howard requested changes
I have looked through all the changes and they all look good to me 👍 However when I run the unit/acceptance tests I get one failure in improver_tests/acceptance/test_checksums.py::test_kgo_checksums. Can you just check that it doesn't do that for you? It could easily be something on my side, but it would be good to check. Thanks.

2023-05-09 08:33 UTC, MoseleyS commented
@Katie-Howard: The tests all pass for me this morning.

2023-05-11 14:21 UTC, Katie-Howard approved these changes
I have had a look at the new acceptance test data and I think that it looks fine. So I'm happy with all the changes 👍

2023-05-12 10:01 UTC, merged