Mobt 496 enforce forecast between references
metoppv/improver pull request #1907
Opened 2023-06-02 13:08 UTC by brhooper

Addresses #1900 
Acceptance test data: 

Adds functionality to enforce forecast to be within lower and upper bounds derived from linear functions of a reference forecast. This extends functionality implemented in #1900 .

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-06-06 14:22 UTC, Katie-Howard requested changes
I've had a look through these changes, and  they generally look fine. I just have one question to be addressed. I've also had a little look at the acceptance test data and left a comment on that too. I couldn't see any data in the new file, so if you could check that please?

2023-06-07 14:17 UTC, Katie-Howard approved these changes
These changes all look fine. I reran all the tests and they passed fine 👍

2023-06-13 16:07 UTC, mspelman07 requested changes
Thanks Ben. Generally looks good, just a few small queries.

2023-06-14 13:24 UTC, brhooper commented on improver/cli/enforce_consistent_forecasts.py
>  def process(
Removed now, thanks for pointing this out

2023-06-14 13:25 UTC, brhooper commented on improver/utilities/enforce_consistency.py
> +                "The units in the forecast and reference cubes do not match. The"
Added a `try` ... `except` block to attempt to convert units, raising the existing error if an exception is raised.

2023-06-14 13:26 UTC, brhooper commented on improver/utilities/enforce_consistency.py
>              if forecast.name().startswith("probability_of"):
Thanks for highlighting this, I was looking for just such a function, without success, when initially making the changes, so this is very helpful

2023-06-14 13:26 UTC, brhooper commented on improver/utilities/enforce_consistency.py
>              raise ValueError(msg)
Added to the docstring

2023-06-15 15:08 UTC, mspelman07 requested changes
All the changes look good, just one tiny thing and I'm happy to approve.

2023-06-19 07:32 UTC, brhooper commented on improver/utilities/enforce_consistency.py
> +                comparison_operator are lists when ther are not all lists.
Corrected

2023-06-19 08:33 UTC, mspelman07 approved these changes

2023-06-19 08:42 UTC, merged