MOBT-494: Cube title setting in weather symbol code
metoppv/improver pull request #1912
Opened 2023-06-15 14:49 UTC by bayliffe

Adds the option to manually set the title attribute for weather symbols output. This enables the attribute to be set as desired, including in situations where the input cubes do not share a common title, resulting in no title being set otherwise.

This change is needed for the site-specific phase change work. In the new chains that produce weather symbols from spot forecasts, the rain / sleet / snow inputs have been spot-extracted prior to realization collapse and cycle blending. The weighted blending plugin inherits the PostProcessingPlugin class, meaning all titles are prefixed "Post processed". As a result:
- usual spot extracted outputs used as inputs to the wx have the title "MOGREPS-G Spot Values"
- the phase diagnostics have used as inputs to the wx have the title "Post-Processed MOGREPS-G Spot Values"
- the generate_mandatory_attributes code returns a default unset title attribute as the title is no longer common between all inputs.

This change will be accompanied by an app config change in the suite to manually set the weather symbols output title for the spot-forecast generated weather symbols.

Acceptance test data: https://github.com/metoppv/improver_test_data/pull/15

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-06-15 15:42 UTC, bayliffe commented
@MoseleyS KGO title updated to be metadata compliant.

2023-06-19 14:39 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've just added a minor query related to the checksum.

2023-06-20 06:49 UTC, bayliffe commented on improver_tests/acceptance/SHA256SUMS
> +a51691b4b7b6f8661804554eecf47440ec8353c80d9a779d06ea4b0effbd5b42  ./wxcode/basic/kgo_titled.nc
Yeah, no idea what happened there. Checksums recreated and pushed.

2023-06-20 07:10 UTC, gavinevans approved these changes

2023-06-21 07:53 UTC, brhooper approved these changes
This all looks fine, tests pass.

2023-06-21 07:57 UTC, merged