Account for orography when vertically interpolating falling-levels at sea points
metoppv/improver pull request #1935
Opened 2023-09-05 13:12 UTC by brhooper

Addresses https://github.com/metoppv/mo-blue-team/issues/558
Notebook: https://github.com/MetOffice/improver_aux/pull/399

Updates vertical interpolation of precipitation falling-levels for sea points to account for orography. 
Adds test for new functionality.

The notebook linked above demonstrates how the negative sleet probabilities arise and also shows that this change does actually fix the problem.

Description

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-09-06 07:51 UTC, MoseleyS requested changes
The method is fine. Just needs an explanation in the code.

2023-09-06 07:51 UTC, MoseleyS commented on improver/psychrometric_calculations/psychrometric_calculations.py
> +                Cube of orography (m).
Please add an explanation into the doc-string as to why we are adding the orography of sea points here. Something like: "Not all sea points are at sea level (e.g. Sea of Azov) and we account for this by adding the orography altitude to the phase_change_level_data where this interpolation is applied".

2023-09-06 10:16 UTC, MoseleyS commented on improver/psychrometric_calculations/psychrometric_calculations.py
> +        however this is not always the case. The orography altitude is  added to phase
```suggestion
        however this is not always the case. The orography altitude is added to phase
```

2023-09-06 10:17 UTC, MoseleyS requested changes
Double space!

2023-09-06 10:19 UTC, brhooper commented on improver/psychrometric_calculations/psychrometric_calculations.py
> +        however this is not always the case. The orography altitude is  added to phase
Woops! Should be fixed now.

2023-09-06 10:35 UTC, MoseleyS approved these changes

2023-09-07 08:12 UTC, bayliffe requested changes
One miniscule comment.

2023-09-07 08:59 UTC, brhooper commented on improver/psychrometric_calculations/psychrometric_calculations.py
> +                Cube of orography (m).
Thanks @bayliffe - I've updated this docstring to match the other docstrings where `orography` is an array.

2023-09-07 10:04 UTC, bayliffe approved these changes

2023-09-07 10:04 UTC, merged