Refactor weather code plugins and CLIs
metoppv/improver pull request #1944
Opened 2023-09-22 11:49 UTC by MoseleyS

As Enhancing Post Processing Science Lead, I want the IMPROVER weather code plugin to be refactored so that I can run a precipitation type code configuration.

The essential changes are around metadata. The output cube name and categorical attributes are now derived from the decision tree, which has been updated as a result and is now also a required input to the modal categories plugin.

To achieve this, I have done some refactoring:

- code and acceptance test data moved to directories named `categorical`
- CLI names changed:
  - `wxcode` -> `categorical`
  - `wxcode_modal` -> `categorical-modes`
- Both these CLIs now require the decision tree, with the key name changing from `wxtree` to `decision-tree`
- Plugin names changed:
  - `WeatherSymbols` -> `ApplyDecisionTree`
  - `ModalWeatherCode -> `ModalCategory`
- Several internal variable names and comments have been updated to be more generic.
- Meta data definitions of the cube name, attribute names and contents have moved out of the code and into the decision tree.
- Grouping and day -> night mapping have moved out of the code and into the decision tree.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-09-27 11:53 UTC, mspelman07 requested changes
Thanks Stephen. A few comments mostly around clarifying some docstrings but otherwise this looks good.

2023-09-27 14:17 UTC, MoseleyS commented on doc/source/extended_documentation/categorical/build_a_decision_tree.rst
> +    "meta": {
Clause added

2023-09-27 14:20 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +        """
Added

2023-09-27 14:20 UTC, MoseleyS commented on improver/categorical/decision_tree.py
>              for node, query in self.queries.items():
Changed

2023-09-27 14:23 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +        Create an empty categorical cube
Updated

2023-09-28 09:51 UTC, mspelman07 requested changes
I'm happy with the changes made. 

The only remaining references to weather symbols that I can find (ignoring tests) are in the following locations:

improver.categorical.utilities.categorical_attributes
improver.developer_tools.metadata_interpreter.MOMetadataInterpreter (in function run)

The categorical utilities just has a few variables called wx_keys which probably wants updating but I'm not sure about the developer_tools one?

2023-10-03 09:16 UTC, MoseleyS commented
> improver.categorical.utilities.categorical_attributes improver.developer_tools.metadata_interpreter.MOMetadataInterpreter (in function run)
> 
> The categorical utilities just has a few variables called wx_keys which probably wants updating but I'm not sure about the developer_tools one?

I've updated the variable names in both files. This allows us to add other categorical data to the metadata interpreter in the future, if required.

2023-10-03 13:23 UTC, mspelman07 submitted a review, later dismissed

2023-10-20 16:11 UTC, gavinevans requested changes
Thanks @MoseleyS 👍 

I've added some very minor comments.

2023-11-01 12:32 UTC, MoseleyS commented on doc/source/extended_documentation/categorical/build_a_decision_tree.rst
> +The first leaf node above is encoded as follows::
Updated

2023-11-01 12:32 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +    def _is_decision_node(key: str, query: Dict) -> bool:
Thanks. I don't think I could work out a complete type hint that was correct.

2023-11-01 12:33 UTC, MoseleyS commented on improver_tests/categorical/decision_tree/test_ApplyDecisionTree.py
> +from improver.categorical.decision_tree import ApplyDecisionTree
Changed

2023-11-01 12:33 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +        optional_attributes = categorical_attributes(self.queries, self.meta["name"])
Changed

2023-11-01 12:33 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +                categories.data[
Done

2023-11-01 12:33 UTC, MoseleyS commented on improver/categorical/modal_code.py
> +    achieve this the categories are subtracted from an arbitrarily larger
I've modified this, but not quite to your suggestion.

2023-11-01 12:34 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +            self.meta["name"],
changed

2023-11-01 12:35 UTC, MoseleyS commented on improver/categorical/utilities.py
> +            Cube containing only daytime weather symbols.
I'm surprised at how many of these I missed! Changed.

2023-11-01 12:36 UTC, MoseleyS commented on improver/categorical/utilities.py
> +            leaf_target = items.get("leaf", -1)
Yes. Changed.

2023-11-01 12:38 UTC, MoseleyS commented on improver/categorical/utilities.py
> +def day_night_map(decision_tree) -> Dict:
I've added your earlier suggestion here too.

2023-11-01 12:39 UTC, MoseleyS commented on improver_tests/categorical/decision_tree/__init__.py
> +from improver.categorical.utilities import categorical_attributes
Done

2023-11-01 12:42 UTC, MoseleyS commented on improver_tests/categorical/test_utilities.py
> +        self.wxcode = np.arange(31)
Done something equivalent.

2023-11-01 14:11 UTC, MoseleyS commented on improver/categorical/decision_tree.py
> +    def _is_decision_node(key: str, query: Dict) -> bool:
Agreed. I've moved it into utilities and added tests. It is now used in update_tree_thresholds too.

2023-11-02 08:39 UTC, gavinevans requested changes
Thanks for the updates, @MoseleyS 👍 

I've added one trivial comment.

2023-11-02 09:25 UTC, MoseleyS commented on improver/categorical/modal_code.py
> +    number prior to calculating the mode, and this operation reversed before the
Grammar corrected

2023-11-02 09:37 UTC, gavinevans approved these changes

2023-11-14 13:14 UTC, merged