Wet bulb freezing level
metoppv/improver pull request #1949
Opened 2023-10-02 16:00 UTC by mspelman07

This PR adds in the ability to calculate a Wet bulb freezing level from a wet-bulb temperature on height levels.

Most of the changes for this PR are simply renaming variables to be more agnostic and apply to height and pressure coordinates rather than just pressure. The main changes are for the plugin ExtractPressureLevel (renamed to ExtractLevel). The core changes in this PR are:

- Plugin now looks first for a pressure coordinate and then a height coordinate. Depending on which it finds will determine whether a height or pressure level are extracted.
- In writing this plugin I found that stratify has an EXTRAPOLATE_NEAREST keyword which will automatically do what fill_in_bounds was previously doing so I have replaced this.
- I have also added an extra argument to the stratify interpolation of rising=False. This tells stratify which direction we expect the variable to change and solves a problem if there was a temperature inversion between the first two valid points (see notebook below)  
- CLI added to calculate wet bulb freezing level 

To show my changes to the ExtractLevel plugin haven't changed how the plugin works (except where they should change it) I have plotted a few profiles of what it extracted previously and what it extracts now.

Acceptance_test_data:

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2023-10-03 10:14 UTC, MoseleyS requested changes
Just a doc-string change needed.

A comment for your notebook: Surface temperature inversions like your final example are quite common, although they are usually much shallower than that. We won't have seen this in the hail output because surface temperature inversions are associated with stable, nocturnal, non-convective weather, when hail is not possible.

2023-10-03 12:01 UTC, mspelman07 commented on improver/cli/wet_bulb_freezing_level.py
> +    The height level at which the wet-bulb temperature first drops below 237.15K
Done

2023-10-03 12:01 UTC, mspelman07 commented on improver/cli/wet_bulb_freezing_level.py
> +    starts below 237.15K the lowest height on the cube is returned.
Done

2023-10-03 12:17 UTC, MoseleyS approved these changes

2023-10-09 13:02 UTC, brhooper reviewed
Thanks @mspelman07, I've just added a few comments, mostly about docstrings.

2023-10-09 14:18 UTC, MoseleyS commented on improver/utilities/cube_extraction.py
> +        """Extracts the pressure or height level (depending on which is present on the cube)
For Met Office StaGE data, there are no data that have both a pressure and a height coordinate, and I don't think it is possible to have one as the relationship between pressure and height requires knowledge of altitude and density. We have data of height of pressure levels for this purpose.
While it is possible to construct a cube with both a height and a pressure coordinate, it doesn't make sense to do so. Perhaps the safest approach is to raise a `NotImplementedError` if an input cube contains both these coordinates.

2023-10-10 13:13 UTC, mspelman07 commented on improver/cli/wet_bulb_freezing_level.py
> +    height level on the cube is returned. In grid square where the temperature
Done

2023-10-10 13:14 UTC, mspelman07 commented on improver/cli/wet_bulb_freezing_level.py
> +    The height level at which the wet-bulb temperature first drops below 273.15K
I've extended the sentence to clarify what I meant.

2023-10-10 13:30 UTC, mspelman07 commented on improver/utilities/cube_extraction.py
> +        """Extracts the pressure or height level (depending on which is present on the cube)
I've taken Stephen's suggestions and added in an error in this case as well as an extra test to check this error.

2023-10-10 13:45 UTC, brhooper commented on improver/utilities/cube_extraction.py
> +        """Extracts the pressure or height level (depending on which is present on the cube)
Stephen's suggestion is more sensible than mine, so that's probably for the best!

2023-10-10 13:46 UTC, brhooper approved these changes
Thanks @mspelman07, I'm happy to approve this now

2023-10-10 13:47 UTC, merged