make gradient consider distance
metoppv/improver pull request #1985
Opened 2024-03-13 19:01 UTC by MO-PeterJordan

The existing gradient module does not divide through by the distance between grid points. Instead it divides through by the angular separation, resulting in units of original-units * deg^-1. This PR changes that to divide through by distance in meters, so that the resulting units are original-units * m-1. This is what we would naturally expect, and allows eg. relative voticity to be calculated with the correct units of s^-1.

Potential issues:
When calculating the gradient of wind speed (m/s) Iris presents the resulting units as Hz, which might be confusing for a gradient. However, grad_cube.units == s^1 returns true, so iris' units logic for downstream applications will be fine.

Absolute precision requirement has been reduced in the tests from e-8 to e-4 as this threshold was being breached in cases with very large gradients (>6 orders of magnitude between adjacent grid cells) where interpolation where required to recover the original grid shape . This seems to be to do with the way iris does linear interpolation. However O(10^6) gradients between adjacent cells seem unlikely to occur for meteorological parameters. Furthermore, +/-0.0001 should be enough precision for gradients of most if not all parameters.

2024-03-22 13:12 UTC, mspelman07 requested changes
Thanks for this Peter. The first Improver PR is always the hardest to get right.

I've added comments to the main plugins changes you've made. I haven't reviewed the tests yet but I felt I'd given you enough comments to keep you busy for now. I also notice there isn't a CLI for calculating the gradient. I don't know if that is part of this PR or will be part of another PR? We'll need it when we need to call the functions you've written from the suite.

2024-03-26 11:12 UTC, MO-PeterJordan reviewed
Most requested changes made. Some responded to with comments.

2024-03-27 18:13 UTC, MO-PeterJordan commented
I think the CLI should be a separate PR, there's plenty on this one already!
I don't think I'd actually _need_ one for relative vorticity, as that will call the gradient module, which itself calls the distance module; however, it might be standard practice that all new modules get CLIs?

2024-03-28 16:01 UTC, MoseleyS requested changes
I've suggested quite a lot of tweaks. Feel free to disagree where you feel strongly about it.

I haven't had time to finish reviewing all the tests - I'll do that when I re-review this.

2024-04-02 15:38 UTC, MO-PeterJordan commented on improver_tests/utilities/test_DistanceBetweenGridPoints.py
> +    input_cube = make_latlon_test_cube(
done

2024-04-02 15:38 UTC, MO-PeterJordan commented on improver_tests/utilities/test_DistanceBetweenGridPoints.py
> +    input_cube = make_latlon_test_cube(
done

2024-04-02 15:39 UTC, MO-PeterJordan commented on improver_tests/utilities/test_DistanceBetweenGridPoints.py
> +    input_cube = make_transverse_mercator_test_cube((3, 2))
done

2024-04-02 15:39 UTC, MO-PeterJordan commented on improver_tests/utilities/test_DistanceBetweenGridPoints.py
> +    input_cube = make_latlon_test_cube(
done

2024-04-03 12:54 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +        x_distances_degrees = np.tile(lon_diffs, (lats_as_col.shape[0], 1))
Have simplified this method.

2024-04-03 12:55 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +        ).transpose()
Done

2024-04-03 13:06 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +        y_distances = calculate_grid_spacing(cube, axis="y", units="meters")
Changed to y_grid_spacing

2024-04-03 13:09 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +            x_diff:
I don't love this either, but struggling to think of anything better. The diff cubes are only there to provide coordinates with the correct dimensions to apply to the distances cubes. Open to suggestions for how to communicate this in a variable name though.

2024-04-03 13:21 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +                Name of the cube to be created.
Code deleted and below suggestion implemented to replace

2024-04-03 13:22 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +    @classmethod
Classmethods now all removed due to refactor.

2024-04-03 13:34 UTC, MO-PeterJordan reviewed
Ready for re-review. Have implemented or replied to all review comments.
Also refactored the distance calculations to separate out the logic specific to different types of cubes a bit better. Hopefully makes it easier to follow.

2024-04-03 13:34 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
Done

2024-04-03 15:34 UTC, MoseleyS requested changes
Looking good, but I've found a few more things to tweak.

2024-04-03 15:34 UTC, MoseleyS commented on improver/utilities/spatial.py
>              A cube containing the horizontal distances between the grid points of the input
```suggestion
            A cube containing the x-axis distances between the grid points of the input
```

2024-04-03 15:34 UTC, MoseleyS commented on improver/utilities/spatial.py
>              cube in meters.
```suggestion
            A cube containing the y-axis distances between the grid points of the input
            cube in metres.
```

2024-04-03 15:34 UTC, MoseleyS commented on improver/utilities/spatial.py
> +            - Cube of vertical distances.
```suggestion
            - Cube of x-axis distances.
            - Cube of y-axis distances.
```

2024-04-05 13:17 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +class BaseDistanceCalculator:
Done

2024-04-05 16:28 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
>              cube in meters.
Fixed

2024-04-05 16:32 UTC, MO-PeterJordan commented on improver/utilities/spatial.py
> +        """Constructs an output cube with units of meters."""
Done

2024-04-09 07:20 UTC, MoseleyS requested changes
I see that this PR now has some conflicts with master, which prevents the CI tests from running. You'll need to sort this out before the PR can be approved.

2024-04-09 07:20 UTC, MoseleyS commented on improver_tests/utilities/test_DistanceBetweenGridPoints.py
> +#TODO: do I still need this now that set_up_variable_cube supports different x and y grid spacing?
Added TODO?

2024-04-09 07:20 UTC, MoseleyS commented on improver_tests/utilities/test_GradientBetweenAdjacentGridSquares.py
> +def regrid_x_with_wrap_around_interpolation_for_edge_points(data):
These methods need doc-strings too

2024-09-20 01:36 UTC, closed without merging

2024-09-20 06:13 UTC, MoseleyS commented
This work has been completed in other PRs.