Height of max
metoppv/improver pull request #2020
Opened 2024-07-24 15:51 UTC by mspelman07

This PR is superseeding PR: https://github.com/metoppv/improver/pull/2012 as I cannot push changes to the branch.
Acceptance_test_data: https://github.com/metoppv/improver_test_data/pull/51/files

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature

2024-07-30 08:24 UTC, MoseleyS requested changes
Nice simple function and tests - easy to follow.

I haven't looked at the acceptance test data yet, but before I do, I think the units need fixing.

2024-08-01 11:49 UTC, mspelman07 commented on improver/utilities/cube_manipulation.py
> +    return height_of_max
Done.

2024-08-01 11:52 UTC, mspelman07 commented on improver/utilities/cube_manipulation.py
> +            where the maximum occurs at more than one height).
Done. I've ended up doing the opposite of your suggestion and having find_lowest have a default value of True but I don't think this actually matters.

2024-08-01 11:52 UTC, mspelman07 commented on improver/utilities/cube_manipulation.py
> +        original cube is used.
Done

2024-08-02 08:08 UTC, MoseleyS approved these changes

2024-08-02 08:10 UTC, merged