Categorical fix for Deterministic data
metoppv/improver pull request #2038
Opened 2024-10-04 14:58 UTC by mspelman07

Ticket: https://metoffice.atlassian.net/browse/EPPT-1683

This ticked is fixing a bug with the categorical plugin when using deterministic data and requiring multiple diagnostics/floats to be evaluated for a node. 

It also fixes the order of operation part of the code which previously always evaluated operators in the order divide,multiply, add,subtract. This isn't quite write as divide and multiply have the same precidence and should be evaluated from left to right. Ditto for add and subtract.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2024-10-10 13:08 UTC, seshukolusu16 approved these changes

2024-10-11 09:01 UTC, MoseleyS requested changes

2024-10-11 15:12 UTC, mspelman07 commented on improver_tests/categorical/decision_tree/test_ApplyDecisionTree.py
> +            )
Done and I've extended the test to include the two variables at the end of the conditon

2024-10-11 15:13 UTC, mspelman07 commented on improver/categorical/decision_tree.py
> +            thresholds = test_conditions["probability_thresholds"]
I agree with you. I've reverted the changes to the that part and updated the comment as we discussed.

2024-10-14 09:53 UTC, MoseleyS approved these changes
I'm happy now.
I did spend some time considering whether the equation in the test needed to be changed to prove that the operation order was being applied as expected (it currently gives the right result either way), but I've found another pre-existing test that proves that the order of operations are being applied logically.

2024-10-14 09:54 UTC, MoseleyS commented
Failing tests are not related to this PR.

2024-10-14 09:54 UTC, merged