Adding a plugin to calculate the virtual temperature
metoppv/improver pull request #2058
Opened 2024-12-03 09:32 UTC by mo-philrelton

Address: https://metoffice.atlassian.net/browse/EPPT-1965

This PR adds a plugin to calculate the virtual temperature based on the air temperature and humidity mixing ratio.

No CLI added due to the move to the DAG runner.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

CLA
 - [x] If a new developer, signed up to CLA

2024-12-05 16:31 UTC, Katie-Howard requested changes
I've looked through the changes and I'm generally happy with them:

- The virtual temperature plugin looks like it does what it's supposed to
- The unit tests that have written look sensible and all run fine
- The PR is failing due to the PR standards - I think it's just something to do with adding yourself as a contributor. I think it's because in the email address you are phil.relton@metoffice.gov.uk but you have put your name as Philip it doesn't like this. It might be worth changing that and see if it then passes that test?
- I've left a couple of comments about your comments but they are very minor.

2024-12-06 09:14 UTC, mo-philrelton commented on improver/virtual_temperature.py
> +    """Calculates the virtual temperature from temperature and ."""
I did, but I have now changed this string to `"""Plugin class to handle virtual temperature calculations."""` to better answer your second comment.

2024-12-06 09:14 UTC, mo-philrelton commented on improver/virtual_temperature.py
> +        Calculate the virtual temperature from temperature and humidity mixing ratio.
You're right it's a little repetitive. I have changed the class docstring.

2024-12-06 15:22 UTC, mo-philrelton commented
The cause of the failing tests was a poorly set up git config. Rather than confusing this PR with further commits and rewriting the history to the new configuration I will close this PR and open a new one.

2024-12-06 15:22 UTC, closed without merging