added the lightning_flash_accumulation_in_vicinity cell method missing from
metoppv/improver pull request #2064
Opened 2024-12-10 16:47 UTC by maxwhitemet

Addresses [#802 ](https://github.com/metoppv/mo-blue-team/issues/802)

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2024-12-16 10:55 UTC, lambert-p reviewed
I have reviewed your code, it is looking good and I can't see any changes that need to be made. I will put it into second review.

2024-12-17 10:24 UTC, brhooper requested changes
Thanks @maxwhitemet, these changes look as I expected them to. 

I've attempted to run all of the IMPROVER tests and get failures for acceptance tests in `improver_tests/acceptance/test_lightning_from_cape_and_precip.py`. I think that the KGOs for these tests need updating to include the new cell method.

2024-12-17 14:45 UTC, brhooper approved these changes
Thanks @maxwhitemet, this all looks fine to me.

I think you'll need to pull master back into this branch before it can be merged, so that the fix to the Github actions can be included.

2024-12-18 12:20 UTC, lambert-p approved these changes

2024-12-18 13:10 UTC, merged