MOBT-809: Backport weather symbol release changes into master
metoppv/improver pull request #2065
Opened 2024-12-11 11:36 UTC by bayliffe

Backport [release changes](https://github.com/metoppv/mo-blue-team/issues/801) for wx modal derivation into master. These changes primarily aimed at including the cloud component from wet symbols in dry day symbol derivation.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

2024-12-30 12:18 UTC, Kat-90 reviewed
Mostly all good, just one question about the checksums. I also have a failing test on the test_kgo_checksums so maybe there is something going on there but the CI checks have passed for you so it could be a me problem.

2024-12-30 12:18 UTC, Kat-90 commented on improver_tests/acceptance/SHA256SUMS
> +391a9bd50824318fb8f147db3b14bcd56f5b0f0e0d5479b3579e08d70ef6ba77  ./weather-symbol-modes/spot_ties/new_kgo.nc
Is this new line right? I can't see a "new_kgo" in the original and is it supposed to have the same checksum as the one above?

2025-01-06 13:13 UTC, bayliffe commented on improver_tests/acceptance/SHA256SUMS
> +391a9bd50824318fb8f147db3b14bcd56f5b0f0e0d5479b3579e08d70ef6ba77  ./weather-symbol-modes/spot_ties/new_kgo.nc
Nope, my bad. Removed. I've also rebased this branch and the acceptance test data on the most recent version of master and re-run the acceptance tests to ensure everything works.

2025-01-07 16:38 UTC, Kat-90 submitted a review, later dismissed
Thanks for the change, all tests passing for me now.

2025-01-10 17:32 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've added some minor comments.

2025-01-10 17:32 UTC, gavinevans commented on improver/categorical/utilities.py
> +def dry_map(decision_tree: Dict[str, Dict[str, Union[str, List]]]) -> Dict:
We should probably have some sort of standalone unit tests for this function, similar to `day_night_map` even if the bulk of the testing is effectively done within `test_ModalFromGroupings.py`.

2025-01-10 17:32 UTC, gavinevans commented on improver_tests/categorical/decision_tree/test_ModalFromGroupings.py
> +        # dominant dry code, leading to an overcast symbol overall (8).
This description doesn't seem to make sense, given that the result from the test seems to be 1 (sunny), rather than overcast.

2025-01-13 08:36 UTC, bayliffe commented on improver_tests/categorical/decision_tree/test_ModalFromGroupings.py
> +        # dominant dry code, leading to an overcast symbol overall (8).
Yes, I must have been adding and deleting tests and fully mangled this one. Fixed.

2025-01-13 09:05 UTC, bayliffe commented on improver/categorical/utilities.py
> +def dry_map(decision_tree: Dict[str, Dict[str, Union[str, List]]]) -> Dict:
Added.

2025-01-13 10:35 UTC, gavinevans approved these changes

2025-01-14 09:51 UTC, merged