IM-Suite-2102: Threshold bug fix for vicinity processing of masked fields
metoppv/improver pull request #2071
Opened 2024-12-19 14:41 UTC by bayliffe

Bug fix to threshold plugin. The masking was being lost in the vicinity processing following last year's refactor. This corrects the issue.

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

2024-12-20 14:55 UTC, gavinevans requested changes
Thanks @bayliffe 👍 

I've added one very minor comment, but otherwise this looks fine.

2025-01-03 12:18 UTC, Kat-90 submitted a review, later dismissed
Separate to Gavin's comment. Reviewed the code and ran the tests alongside the test_data changes. All looks good to me.

2025-01-06 11:09 UTC, bayliffe commented on improver_tests/acceptance/test_threshold.py
> +        / "precip_accumulation_thresholds.json",
Done.

2025-01-06 15:28 UTC, gavinevans approved these changes

2025-01-06 15:44 UTC, merged