Mobt 2066 convert forecast to climatological anomaly
metoppv/improver pull request #2072
Opened 2024-12-31 10:24 UTC by maxwhitemet

Addresses #2066 

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

The structure of the new CalculateClimateAnomalies class follows that agreed with @brhooper 
- Initialisation
- Verification of inputs
	- Matching standard names
	- Matching units
	- Matching grids
	- Matching time coordinates
- Calculation of anomalies: both unstandardised and standardised
- Creation of output cube with appropriate metadata

2025-01-16 09:33 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        return start_time, end_time
I have replaced all instances of `_get_cube_time_range()` with the `.coord('time').bounds()` method.

2025-01-16 14:12 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        return cubes_to_check
Added.

2025-01-16 14:12 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        use of cubes with referring to different physical phenomenon
Done.

2025-01-16 16:39 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +                )
Added each bullet point. I solved point 3 by setting another parameter in the CalculateClimateAnomalies class called 'ignore_temporal_mismatch' with default value False that when set to True skips this check.

2025-01-17 15:46 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +                )
Done. 
I noticed I made a mistake in my previous commit here: the variance cube will have units squared. I have thus not used set() here, but added a further check on whether variance cube units are appropriate, if this cube is provided as an input that is.

2025-01-17 16:21 UTC, maxwhitemet commented on improver_tests/acceptance/SHA256SUMS
> +e488d0417ccddf388375c137e3527fa8c2f78e1abee52d6db54e5469900702ea  ./freezing-rain/three_hour/kgo.nc
Done.

2025-01-17 16:22 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        variance_cube: Optional[Cube] = None,
Done. Noted for future.

2025-01-20 10:29 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +                )
I don't think that it is safe to use the sum function for this test. Consider 2 cubes with spot indices as follows:

1. Cube 1 points = [1, 4]
2. Cube 2 points = [2, 3]

I think that your test will pass given these 2 cubes, which is not what we want to happen.

2025-01-28 14:45 UTC, brhooper requested changes
Thanks @maxwhitemet - I think we're heading in the correct direction on this. I've added some comments to the plugin changes you've made. Once we get the plugin finalised we can talk in more depth about the tests, though I will say that codecov bot thinks that some lines of code are not being touched by the tests.

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +                    )
This is unnecessary as you have already checked that the mean and variance cubes have the same time bounds.

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +        )
```suggestion
        name, units = self._generate_output_name_and_units(
            diagnostic_cube, variance_cube
        )
```

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +        )
```suggestion
        output_cube = self._add_reference_epoch_metadata(
            output_cube, diagnostic_cube, mean_cube
        )
```

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +    @staticmethod
```suggestion
    @staticmethod
```

This can be removed once you start using `self` within the function

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +            variance_cube is not None
This can be removed

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +            variance_cube is not None
```suggestion
    @staticmethod
    def _generate_output_name_and_units(diagnostic_cube, standard_anomaly=False) -> str:
        """Get suitable output name and units from input cube metadata"""
        anomaly_cube = diagnostic_cube.copy()
        new_name = None
        new_units = anomaly_cube.units
        # If standard_anomaly is true, the output is a standard anomaly and units are changed
        suffix = "_standard_anomaly" if standard_anomaly else "_anomaly"
        new_units = "1" if standard_anomaly else anomaly_cube.units

        try:
            anomaly_cube.standard_name = (
                anomaly_cube.standard_name + suffix
            )
            new_name = anomaly_cube.standard_name
        except ValueError:
            anomaly_cube.long_name = (
                anomaly_cube.standard_name + suffix
            )
            new_name = anomaly_cube.long_name
```

I've suggested some changes to this function. Additionally, as we're creating `anomaly_cube` here, I think that this should all be moved within `_create_output_cube` to avoid creating unnecessary copies of data in memory.

I've also suggested a change to the inputs which will be rendered redundant if the functionality is moved, however I'll explain it anyway. We aren't actually using `variance_cube` here, except insofar as we check that it exists. We could check that it is exists elsewhere, then simply pass `True` or `False` in to this function instead.

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +                )
```suggestion
                errors.append(
                    f"The variance cube must be the diagnostic cube units squared."
                    f"The following units were found: {variance_cube.units}, {diagnostic_cube.units}"
                )
```

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +        """
Should add a line to this doc-string to explain that `output_cube` is modified in place

2025-01-28 14:45 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +                )
```suggestion
        if not self.ignore_temporal_mismatch:
        diagnostic_max = diagnostic_cube.coord("time").cell(-1)
        diagnostic_min = diagnostic_cube.coord("time").cell(0)
            if not (
                diagnostic_max
                <= mean_cube.coord("time").cell(0).bound[-1]
                diagnostic_min
                >= mean_cube.coord("time").cell(0).bound[0]
            ):
                errors.append(
                    f"The diagnostic cube's time points must fall within the bounds of the mean cube. The following was found:"
                    f"diagnostic cube maximum: {diagnostic_max},"
                    f"diagnostic cube minimum: {diagnostic_min},"
                    f"mean cube upper bound: {mean_cube.coord('time').cell(0).bound[-1]},"
                    f"mean cube lower bound:{mean_cube.coord('time').cell(0).bound[0]}"
                )
```

I think that this change will allow multi-time cubes to pass through if all of the time points on the diagnostic cube are within the bounds of the climatological values.

2025-01-29 09:07 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            if variance_cube.units != str(diagnostic_cube.units) + "2":
Can this be kept at just '2'? If I multiply two temp cubes, I get 'K2' as the units. 'm2' is also used [here](https://scitools-iris.readthedocs.io/en/latest/userguide/cube_maths.html).

2025-01-29 09:13 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            variance_cube is not None
These lines seem necessary. E.g. wind_speed_anomaly would need to become the long name as it's not a valid standard name.

2025-01-29 09:25 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +            variance_cube is not None
This is an issue with how Github displayed my comment - I was only referring to line 549, which I don't think is doing anything.

2025-01-29 09:34 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +            if variance_cube.units != str(diagnostic_cube.units) + "2":
Ah, you're right.

2025-01-29 16:04 UTC, maxwhitemet commented on improver_tests/utilities/test_mathematical_operations.py
> +    return cube
Added

2025-01-29 16:55 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +                    )
Removed.

2025-01-29 17:10 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +                )
Added

2025-01-30 09:30 UTC, maxwhitemet commented on improver_tests/utilities/test_mathematical_operations.py
> +    return cube
Implemented

2025-02-06 12:30 UTC, brhooper requested changes
Thanks @maxwhitemet, I think we're getting there with this PR. I've left a few comments on the plugin itself. We've also had a chat about how the unit tests can be re-written to make it easier for people reading the code to understand what is being tested, as well as sketching out what tests are required.

2025-02-06 12:30 UTC, brhooper commented on improver_tests/utilities/test_mathematical_operations.py
> +        plugin.verify_units_match(diagnostic_cube, mean_cube, variance_cube)
```suggestion
@pytest.mark.parametrize("error_to_raise", ["mean", "variance"])
def test_verify_units_mismatch(diagnostic_cube, mean_cube, variance_cube, error_to_raise):
    """Test that the plugin raises a ValueError if the units of the diagnostic and another cube mismatch"""
    plugin = CalculateClimateAnomalies()
    if error_to_raise == "mean":
        mean_cube.units = "kittens"
        with pytest.raises(ValueError, match="The mean cube must have the same units as the diagnostic cube"):
            plugin.verify_units_match(diagnostic_cube, mean_cube, variance_cube)
    else:
        variance_cube.units = "K"
        with pytest.raises(ValueError, match="The variance cube must have the same units as the diagnostic cube"):
            plugin.verify_units_match(diagnostic_cube, mean_cube, variance_cube)
```

As an of how the tests can be rewritten to make what they're doing a bit clearer:
1. Pytest fixtures can be used to create default cubes
2. We can explicitly modify the default cubes within each test to demonstrate how we are trying to cause a given error
3. We can explicitly include the expected error message using the `match` input, to demonstrate which error is being raised and confirm that it is the error we expect.

2025-02-06 15:41 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        suffix = "_standard_anomaly" if self.standard_anomaly else "_anomaly"
Added

2025-02-06 15:42 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +    ) -> None:
That's interesting. Thanks Ben. Also saves me a few unit tests

2025-02-06 15:50 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        return output_cube
Sorted.

2025-02-06 15:52 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            )
Done

2025-02-06 15:52 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        )
Good point. Done

2025-02-06 15:53 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            if variance_cube.units != str(diagnostic_cube.units) + "2":
Done

2025-02-06 15:59 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            raise ValueError("The spatial coordinates must match.")
Good points. Added

2025-02-07 17:20 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +            variance_cube is not None
Added

2025-02-10 16:22 UTC, maxwhitemet commented on improver_tests/utilities/test_mathematical_operations.py
> +        plugin.verify_units_match(diagnostic_cube, mean_cube, variance_cube)
Added. Thank you Ben, this is really useful.

2025-02-12 15:46 UTC, brhooper requested changes
Thanks @maxwhitemet, your latest changes have really improved the unit tests. I've made some additional requests for changes, but overall I think that the PR is close to be ready for another review.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time_bounds=time_bounds, time=time)
It's probably worth defining a sensible forecast reference time here too, as currently this fixture is producing a cube with a reference time in 2017 and a validity time in 2024. This isn't strictly a problem for the tests, but a 7 year forecast period looks a bit odd. 

Additionally, I don't think that a temperature cube requires time bounds, as these usually represent an instantaneous quantity.

These changes should also be applied to the other fixture cubes you are defining.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds)
```suggestion
@pytest.fixture
def mean_cube():
    """Fixture for creating a mean cube."""
    data = np.mean([300, 298, 296], dtype=np.float32).reshape(1, 1, 1)
    time_bounds = (datetime(2024, 9, 16, 0, 0), datetime(2024, 10, 16, 0, 0))
    time = datetime(2024, 10, 16, 0, 0)
    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds)
```

We expect the mean cube used in this plugin to represent a mean over an extended period of time. Additionally, the validity time is always at the end of the time bounds by convention in IMPROVER.

This cube should also have a cell method which identifies that the cube is a mean over the time coordinate.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds, units=units)
```suggestion
@pytest.fixture
def variance_cube():
    """Fixture for creating a variance cube"""
    data = np.array(np.var([300, 298, 296]), dtype=np.float32).reshape(1, 1, 1)
    time_bounds = (datetime(2024, 9, 16, 0, 0), datetime(2024, 10, 16, 0, 0))
    time = datetime(2024, 10, 16, 0, 0)
    units = "K2"
    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds, units=units)
```

We expect the mean cube used in this plugin to represent a mean over an extended period of time. Additionally, the validity time is always at the end of the time bounds by convention in IMPROVER. These values for the variance are also a bit large. You could consider using numbers around 1 or 2 instead.

This cube should also have a cell method which identifies that the cube is a variance over the time coordinate.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return site_cube_diagnostic, site_cube_mean, site_cube_variance
```suggestion
@pytest.fixture
def site_cubes():
    """Fixture for creating site cubes."""
    site_cube_diagnostic_data = np.array(
        [305], dtype=np.float32
    )
    site_cube_diagnostic = set_up_spot_variable_cube(site_cube_diagnostic_data, 
                                                     time=datetime(2024, 10, 16, 1, 0))
    
    site_cube_mean_data = np.array([np.mean(
        [300, 298, 296])], dtype=np.float32
    )
    site_cube_mean = set_up_spot_variable_cube(site_cube_mean_data,
                                               time_bounds=(datetime(2024, 9, 16, 0, 0),
                                                            datetime(2024, 10, 16, 10, 0)),
                                                time=datetime(2024, 10, 16, 0, 0))
    site_cube_variance_data = np.array([np.var(
        [300, 298, 296])], dtype=np.float32
    )
    site_cube_variance = set_up_spot_variable_cube(site_cube_variance_data, 
                                                   time_bounds=(datetime(2024, 9, 16, 0, 0),
                                                                datetime(2024, 10, 16, 0, 0)),
                                                    time=datetime(2024, 10, 16, 0, 0),
                                                   units="K2")
    return site_cube_diagnostic, site_cube_mean, site_cube_variance
```
Suggested changes to times are for the reasons outlined in my other comments. Additionally, cell methods should be added to the mean and variance cubes.

These values for the variance are also a bit large. You could consider using numbers around 1 or 2 instead.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +@pytest.fixture
Throughout these fixtures you have repeated uses of the same times (and could add in repeated uses of the same forecast reference times).

You could save some code by defining a fixture which contains all of the required times, which you select as appropriate for each cube being defined.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        site_cube_mean.remove_coord("spot_index")
You could use one of the gridded data cubes here instead, so that we're still testing using cubes which have correct metadata.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        site_cube_variance.coord("spot_index").points = site_cube_diagnostic.coord("spot_index").points + 1
Modifying the diagnostic cube rather than these 2 would save a small amount of processing.

2025-02-12 15:46 UTC, brhooper commented on improver_tests/utilities/test_mathematical_operations.py
> +from improver.utilities.mathematical_operations import (
All changes to this file can be reverted, as we've moved our tests elsewhere, so shouldn't be modifying this.

2025-02-13 09:17 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    plugin.verify_spatial_coords_match(*site_cubes)
Deleted. Thank you.

2025-02-13 09:18 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert True
Deleted. Thank you.

2025-02-13 09:48 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds)
Added the validity time and a cell method. Thank you.

2025-02-13 10:56 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        site_cube_variance.coord("spot_index").points = site_cube_diagnostic.coord("spot_index").points + 1
Thank you. Sorted.

2025-02-13 10:58 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        site_cube_mean.remove_coord("spot_index")
Sorted. Thank you.

2025-02-13 15:30 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +@pytest.fixture
Added. Thank you.

2025-02-13 15:31 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds, units=units)
Added. Thank you.

2025-02-14 09:07 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +@pytest.fixture
Added. Thank you.

2025-02-14 09:20 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time_bounds=time_bounds, time=time)
- Added forecast reference time to diagnostic cubes
- Removed time bounds for diagnostic cubes (not mean or variance)

2025-02-14 09:21 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return site_cube_diagnostic, site_cube_mean, site_cube_variance
- Added cell methods to the mean and variance cubes
- Simplified variance values

2025-02-14 09:26 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    np.testing.assert_allclose(result.data, expected_anomalies, rtol=1e-5)
Moved these separate tests into the tests of basic functionality.

2025-02-14 09:56 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        plugin.verify_time_coords_match(diagnostic_cube, mean_cube, variance_cube)
All sorted. Thank you

2025-02-14 09:56 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "(CellMethod(method='anomaly', coord_names=('reference_epoch',), intervals=(), comments=())" in str(result.cell_methods)
Folded. Thank you.

2025-02-14 09:56 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return site_cube_diagnostic, site_cube_mean, site_cube_variance
All added. Thank you.

2025-02-14 09:57 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time=time, time_bounds=time_bounds, units=units)
Added. Thank you.

2025-02-14 09:58 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    return set_up_variable_cube(data=data, time_bounds=time_bounds, time=time)
- Set forecast reference time to be 6 hours prior.
-Removed time bounds where a diagnostic cube

2025-02-17 14:28 UTC, brhooper requested changes
Thanks @maxwhitemet. I've suggested a few small changes.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
I think we should also check the `reference_epoch` coordinate is correct, for example containing the correct time and time bounds.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
I think we should also check the `reference_epoch` coordinate is correct, for example containing the correct time and time bounds.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
I think we should also check the `reference_epoch` coordinate is correct, for example containing the correct time and time bounds.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert result.long_name == site_cube_diagnostic.name() + "_standard_anomaly"
I think we should also check the `reference_epoch` coordinate is correct, for example containing the correct time and time bounds.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    plugin.verify_time_coords_match(diagnostic_cube, mean_cube, variance_cube)
```suggestion
def test_ignore_temporal_mismatch(diagnostic_cube, mean_cube, variance_cube):
    """Test that the plugin handles requests to ignore temporal mismatch
    between diagnostic cube and mean/variance cube.
    """
    diagnostic_cube.coord("time").points = (
        diagnostic_cube.coord("time").points + 10 * SECONDS_IN_HOUR
    )  # Moves diagnostic bounds outside mean bounds
    
    plugin = CalculateClimateAnomalies(ignore_temporal_mismatch=True)
    result = plugin.process(diagnostic_cube, mean_cube, variance_cube)
    
    assert result.long_name == diagnostic_cube.name() + "_standard_anomaly"
    assert result.units == "1"
    assert "reference_epoch" in [coord.name() for coord in result.coords()]
    assert (
    "(CellMethod(method='anomaly', coord_names=('reference_epoch',), intervals=(), comments=())"
    in str(result.cell_methods)
    )
```
This test should still run the plugin and make the basic checks that the result is as expected. We should also check that the `reference_epoch` coordinate has been constructed correctly, for example that it has the correct time and time bounds.

2025-02-17 14:28 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +        plugin.verify_spatial_coords_match(diagnostic_cube, mean_cube, variance_cube)
```suggestion
def test_error_spatial_coords_mismatch_gridded_data(
    diagnostic_cube, mean_cube, variance_cube
):
    """Test that the plugin raises a ValueError if the spatial coordinates of the diagnostic cube and another cube mismatch"""
    mean_cube.coord("latitude").points = mean_cube.coord("latitude").points + 20
    mean_cube.coord("longitude").points = mean_cube.coord("longitude").points + 20
    plugin = CalculateClimateAnomalies()
    with pytest.raises(ValueError, match="The spatial coordinates must match."):
        plugin.verify_spatial_coords_match(diagnostic_cube, mean_cube, variance_cube)
```
We usually set up the test cubes outside of the `pytest.raises` command.

2025-02-17 15:43 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
Added this code to all instances of this comment: 
```
assert result.coord("reference_epoch")
assert result.coord("reference_epoch").points == mean_cube.coord("time").points
assert result.coord("reference_epoch").bounds == mean_cube.coord("time").bounds
assert result.coord("reference_epoch").units == mean_cube.coord("time").units
```

2025-02-17 15:43 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
assert result.coord("reference_epoch")
assert result.coord("reference_epoch").points == mean_cube.coord("time").points
assert result.coord("reference_epoch").bounds == mean_cube.coord("time").bounds
assert result.coord("reference_epoch").units == mean_cube.coord("time").units

2025-02-17 15:45 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
Sorted by adding this code:
```
assert result.coord("reference_epoch")
assert result.coord("reference_epoch").points == mean_cube.coord("time").points
assert result.coord("reference_epoch").bounds == mean_cube.coord("time").bounds
assert result.coord("reference_epoch").units == mean_cube.coord("time").units
```

2025-02-17 16:11 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert "reference_epoch" in [coord.name() for coord in result.coords()]
Sorted by adding this code:
```
assert "reference_epoch" in [coord.name() for coord in result.coords()]
assert result.coord("reference_epoch").points == mean_cube.coord("time").points
assert np.array_equal(result.coord("reference_epoch").bounds, mean_cube.coord("time").bounds)
assert result.coord("reference_epoch").units == mean_cube.coord("time").units
```

2025-02-17 16:20 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    plugin.verify_time_coords_match(diagnostic_cube, mean_cube, variance_cube)
Implemented your suggested code and added the same reference epoch code as that in prior comments.

2025-02-17 16:41 UTC, maxwhitemet commented
Thank you for your review @brhooper. I have implemented the suggested changes.

2025-02-18 08:36 UTC, brhooper reviewed
Thanks @maxwhitemet, I think I'm happy with this now. I've added 3 very minor comments. I think we might also need to talk about running the formatting tests (black, isort, flake8 etc) detailed [here](https://metoffice.atlassian.net/wiki/spaces/TEPPV/pages/1755676920/Code+Testing) using, for example `bin/improver-tests black`.

I also think that your checking of the `reference_epoch` coordinate could be replaced with a simple function to reduce repeated code. Something like:

```
def check_reference_epoch_coord(result_cube, reference_cube):
    """Check that the reference_epoch coordinate on the result cube is as expected."""
    if "reference_epoch" not in [coord.name() for coord in result_cube.coords()]:
        return False
    else:
        results = []
        results.append(
            result_cube.coord("reference_epoch").points
            == reference_cube.coord("time").points
        )
        results.append(
            np.array_equal(
                result_cube.coord("reference_epoch").bounds,
                reference_cube.coord("time").bounds,
            )
        )
        results.append(
            result_cube.coord("reference_epoch").units
            == reference_cube.coord("time").units
        )
        return all(results)
```
though I'm happy to leave this decision to you/the 2nd reviewer.

Overall, I'm happy to move this ticket into 2nd review now, with you making the 3 minor changes indicated in my comments. Thanks for all your work on this.

2025-02-18 08:36 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +## Testing the plugin's basic functionality
```suggestion
# Testing the plugin's basic functionality
```

2025-02-18 08:36 UTC, brhooper commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +## Testing the plugin's internal verification checks
```suggestion
# Testing the plugin's internal verification checks
```

2025-02-19 12:34 UTC, gavinevans requested changes
Thanks @maxwhitemet 👍 

I've added some comments mainly related to getting rid of the long times from docstrings and code comments, and the addition of type hints.

2025-02-19 13:36 UTC, brhooper commented on improver/utilities/mathematical_operations.py
> +            diagnostic_cube.long_name = diagnostic_cube.standard_name + suffix
Yes, we did.

The problem is that there are some cf-compliant names with the `_anomaly` suffix, but this isn't available for all diagnostics. Additionally, there are no cf-compliant standard names with the `_standard_anomaly` suffix.

@bjwheltor suggested we assign the new cube names to the standard name where possible, and the long name in all other cases. The specific examples given were:
- air_temperature_anomaly (standard name)
- wind_speed_anomaly (long name)
- air_temperature_standardized_anomaly* (long name)

2025-02-19 13:44 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +    assert result.coord("reference_epoch")
Sorted.

2025-02-19 13:44 UTC, maxwhitemet commented on improver_tests/utilities/test_CalculateClimateAnomalies.py
> +## Testing the plugin's internal verification checks
Sorted

2025-02-19 13:52 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +    """Utility functionality to convert an input cube of data to a cube containing anomaly data."""
Added. Thank you.

2025-02-19 14:19 UTC, maxwhitemet commented on improver/utilities/mathematical_operations.py
> +        return diagnostic_cube
Removed the return statement and changed the final type hint to be "None"

2025-02-19 15:25 UTC, maxwhitemet commented on improver_tests/acceptance/SHA256SUMS
Reverted by rebasing and recreating checksums

2025-02-20 09:06 UTC, maxwhitemet commented
Thank you for your review @gavinevans. I have made the requested changes.

2025-02-20 14:19 UTC, gavinevans requested changes
Thanks @maxwhitemet 👍 

I've added a few more minor comments.

2025-02-20 16:20 UTC, maxwhitemet commented
Thanks for the further comments @gavinevans 👍
I have implemented the requested changes.

2025-02-20 17:52 UTC, gavinevans approved these changes

2025-02-21 07:33 UTC, brhooper approved these changes
Thanks @maxwhitemet, this all looks fine to me. Good work.

2025-02-21 07:34 UTC, merged